<?php
/**
 * Search, canonical and structured-data policy for Tra-Vel V2.
 *
 * The graph identifies stable editorial entities and deliberately avoids demo
 * Product, Offer and FAQ markup. Live commercial schema belongs to verified
 * supplier data only.
 *
 * @package TraVelV2
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Keep reviewed guide canonicals independent from map/filter query strings.
 *
 * @param string  $canonical Canonical URL generated by WordPress.
 * @param WP_Post $post      Current post.
 * @return string
 */
function tra_vel_v2_canonical_guide_url( $canonical, $post ) {
	if ( $post instanceof WP_Post && tra_vel_v2_is_destination_guide( $post->ID ) ) {
		return get_permalink( $post->ID );
	}
	return $canonical;
}
add_filter( 'get_canonical_url', 'tra_vel_v2_canonical_guide_url', 10, 2 );

/**
 * Keep public titles destination-neutral and useful outside the former Europe focus.
 *
 * @param array<string, string> $parts Generated document title parts.
 * @return array<string, string>
 */
function tra_vel_v2_document_title_parts( $parts ) {
	$parts['site'] = 'Tra-Vel';

	if ( is_front_page() ) {
		$parts['title'] = __( 'חופשות, טיסות, מלונות ותכנון חכם', 'tra-vel-v2' );
	} elseif ( tra_vel_v2_is_destination_guide() ) {
		$parts['title'] = sprintf(
			/* translators: %s: destination name. */
			__( '%s | מדריך תכנון לישראלים', 'tra-vel-v2' ),
			get_the_title()
		);
	}

	return $parts;
}
add_filter( 'document_title_parts', 'tra_vel_v2_document_title_parts' );

/**
 * Return the public title used by SEO and social plugins that bypass core parts.
 *
 * @param string $title Existing generated title.
 * @return string
 */
function tra_vel_v2_public_seo_title( $title ) {
	if ( is_front_page() ) {
		return __( 'חופשות, טיסות, מלונות ותכנון חכם | Tra-Vel', 'tra-vel-v2' );
	}

	if ( tra_vel_v2_is_destination_guide() ) {
		return sprintf(
			/* translators: %s: destination name. */
			__( '%s | מדריך תכנון לישראלים | Tra-Vel', 'tra-vel-v2' ),
			get_the_title()
		);
	}

	return $title;
}
add_filter( 'wpseo_title', 'tra_vel_v2_public_seo_title' );
add_filter( 'wpseo_opengraph_title', 'tra_vel_v2_public_seo_title' );
add_filter( 'wpseo_twitter_title', 'tra_vel_v2_public_seo_title' );

/**
 * Remove the old Europe-only name from Yoast's WebSite entity.
 *
 * @param array<string, mixed> $data Yoast WebSite schema node.
 * @return array<string, mixed>
 */
function tra_vel_v2_enrich_yoast_website_schema( $data ) {
	$data['name']          = 'Tra-Vel';
	$data['alternateName'] = 'Tra-Vel';
	return $data;
}
add_filter( 'wpseo_schema_website', 'tra_vel_v2_enrich_yoast_website_schema' );

/**
 * Prevent personal pages and faceted map/search combinations becoming crawl traps.
 *
 * @param array<string, bool> $robots Existing directives.
 * @return array<string, bool>
 */
function tra_vel_v2_robots_policy( $robots ) {
	$private_page = is_page_template( 'page-saved.php' ) || is_page_template( 'page-account.php' ) || is_page( array( 'saved', 'account' ) );
	$facet_keys   = array(
		'origin', 'destination', 'depart', 'return', 'adults', 'children',
		'currency', 'sort', 'stops', 'budget', 'hotel_class', 'amenities',
		'neighborhood', 'insurance', 'activities', 'map_lat', 'map_lng', 'map_zoom',
	);
	$has_facets   = (bool) array_intersect( $facet_keys, array_keys( wp_unslash( $_GET ) ) ); // phpcs:ignore WordPress.Security.NonceVerification.Recommended

	if ( $private_page || $has_facets ) {
		$robots['noindex'] = true;
		$robots['follow']  = true;
		unset( $robots['index'], $robots['nofollow'] );
	}
	return $robots;
}
add_filter( 'wp_robots', 'tra_vel_v2_robots_policy' );

/**
 * Build a non-commercial ItemList for the editorial destination directory.
 *
 * Unreviewed destinations are represented as named places without public guide
 * URLs, preventing draft pages or noindex map facets from entering the graph.
 *
 * @return array<string, mixed>
 */
function tra_vel_v2_directory_item_list() {
	$path = TRA_VEL_V2_PATH . '/assets/data/editorial-directory.json';
	$data = file_exists( $path ) ? json_decode( file_get_contents( $path ), true ) : array();
	$destinations = isset( $data['destinations'] ) && is_array( $data['destinations'] ) ? $data['destinations'] : array();
	$items = array();
	foreach ( $destinations as $index => $destination ) {
		$items[] = array(
			'@type'    => 'ListItem',
			'position' => $index + 1,
			'item'     => array(
				'@type'            => 'TouristDestination',
				'name'             => sanitize_text_field( $destination['city'] ?? '' ),
				'containedInPlace' => array(
					'@type' => 'Country',
					'name'  => sanitize_text_field( $destination['country'] ?? '' ),
				),
			),
		);
	}
	return array(
		'@type'           => 'ItemList',
		'numberOfItems'   => count( $items ),
		'itemListElement' => $items,
	);
}

/**
 * Build the Tra-Vel entity graph.
 *
 * @return array<string, mixed>
 */
function tra_vel_v2_schema_data() {
	$site_id = home_url( '/#website' );
	$org_id  = home_url( '/#organization' );
	$graph   = array(
		array(
			'@type'      => 'WebSite',
			'@id'        => $site_id,
			'url'        => home_url( '/' ),
			'name'       => get_bloginfo( 'name' ),
			'inLanguage' => 'he-IL',
			'publisher'  => array( '@id' => $org_id ),
		),
		array(
			'@type' => array( 'Organization', 'TravelAgency' ),
			'@id'   => $org_id,
			'name'  => 'Tra-Vel',
			'url'   => home_url( '/' ),
		),
	);

	if ( is_page_template( 'page-directory.php' ) ) {
		$url = get_permalink( get_queried_object_id() );
		$graph[] = array(
			'@type'      => 'CollectionPage',
			'@id'        => $url . '#webpage',
			'url'        => $url,
			'name'       => get_the_title(),
			'inLanguage' => 'he-IL',
			'isPartOf'   => array( '@id' => $site_id ),
			'mainEntity' => tra_vel_v2_directory_item_list(),
		);
		return array( '@context' => 'https://schema.org', '@graph' => $graph );
	}

	if ( ! is_singular() || ! tra_vel_v2_is_destination_guide() ) {
		return array( '@context' => 'https://schema.org', '@graph' => $graph );
	}

	$post_id   = get_queried_object_id();
	$url       = get_permalink( $post_id );
	$profile   = tra_vel_v2_get_guide_profile( $post_id );
	$author_id = (int) get_post_field( 'post_author', $post_id );
	$author    = $profile['author'] ?: ( get_the_author_meta( 'display_name', $author_id ) ?: 'Tra-Vel' );
	$image     = get_the_post_thumbnail_url( $post_id, 'full' );
	$excerpt   = get_the_excerpt( $post_id );
	$article   = array(
		'@type'            => 'Article',
		'@id'              => $url . '#guide',
		'url'              => $url,
		'headline'         => get_the_title( $post_id ),
		'description'      => $excerpt ? wp_strip_all_tags( $excerpt ) : wp_trim_words( wp_strip_all_tags( get_post_field( 'post_content', $post_id ) ), 34 ),
		'datePublished'    => get_the_date( DATE_W3C, $post_id ),
		'dateModified'     => get_the_modified_date( DATE_W3C, $post_id ),
		'inLanguage'       => 'he-IL',
		'mainEntityOfPage' => array( '@id' => $url . '#webpage' ),
		'isPartOf'         => array( '@id' => $site_id ),
		'author'           => array( '@type' => 'Person', 'name' => $author ),
		'publisher'        => array( '@id' => $org_id ),
	);

	if ( $image ) {
		$article['image'] = esc_url_raw( $image );
	}
	if ( $profile['primary_topic'] ) {
		$article['about'] = array( '@type' => 'TouristDestination', 'name' => $profile['primary_topic'] );
	}
	if ( $profile['is_reviewed'] ) {
		$article['lastReviewed'] = $profile['checked'];
	}

	$citations = array_values(
		array_filter(
			array_map(
				static function ( $source ) {
					return ! empty( $source['url'] ) ? esc_url_raw( $source['url'], array( 'https' ) ) : '';
				},
				$profile['sources']
			)
		)
	);
	if ( $citations ) {
		$article['citation'] = $citations;
	}

	$graph[] = array(
		'@type'      => 'WebPage',
		'@id'        => $url . '#webpage',
		'url'        => $url,
		'name'       => get_the_title( $post_id ),
		'inLanguage' => 'he-IL',
		'isPartOf'   => array( '@id' => $site_id ),
		'about'      => array( '@id' => $url . '#guide' ),
		'breadcrumb' => array( '@id' => $url . '#breadcrumb' ),
	);
	$graph[] = $article;
	$graph[] = array(
		'@type'           => 'BreadcrumbList',
		'@id'             => $url . '#breadcrumb',
		'itemListElement' => array(
			array( '@type' => 'ListItem', 'position' => 1, 'name' => __( 'ראשי', 'tra-vel-v2' ), 'item' => home_url( '/' ) ),
			array( '@type' => 'ListItem', 'position' => 2, 'name' => __( 'יעדים', 'tra-vel-v2' ), 'item' => home_url( '/destinations/' ) ),
			array( '@type' => 'ListItem', 'position' => 3, 'name' => get_the_title( $post_id ), 'item' => $url ),
		),
	);

	return array( '@context' => 'https://schema.org', '@graph' => $graph );
}

/** Print the JSON-LD graph. */
function tra_vel_v2_schema_graph() {
	if ( is_admin() || is_feed() ) {
		return;
	}
	if ( defined( 'WPSEO_VERSION' ) || defined( 'AIOSEO_VERSION' ) || function_exists( 'aioseo' ) ) {
		if ( ! tra_vel_v2_is_destination_guide() ) {
			return;
		}
		$data    = tra_vel_v2_schema_data();
		$article = array_values(
			array_filter(
				$data['@graph'],
				static function ( $node ) {
					return isset( $node['@id'] ) && '#guide' === substr( $node['@id'], -6 );
				}
			)
		);
		if ( $article ) {
			echo '<script type="application/ld+json">' . wp_json_encode( array( '@context' => 'https://schema.org', '@graph' => $article ), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE ) . '</script>';
		}
		return;
	}
	echo '<script type="application/ld+json">' . wp_json_encode( tra_vel_v2_schema_data(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE ) . '</script>';
}
add_action( 'wp_head', 'tra_vel_v2_schema_graph', 20 );

/**
 * Enrich Yoast's canonical Article node instead of printing a duplicate graph.
 *
 * @param array<string, mixed> $data Yoast Article schema.
 * @return array<string, mixed>
 */
function tra_vel_v2_enrich_yoast_article_schema( $data ) {
	if ( ! tra_vel_v2_is_destination_guide() ) {
		return $data;
	}
	$profile = tra_vel_v2_get_guide_profile();
	if ( $profile['primary_topic'] ) {
		$data['about'] = array( '@type' => 'TouristDestination', 'name' => $profile['primary_topic'] );
	}
	if ( $profile['is_reviewed'] ) {
		$data['lastReviewed'] = $profile['checked'];
	}
	$citations = array_values(
		array_filter(
			array_map(
				static function ( $source ) {
					return ! empty( $source['url'] ) ? esc_url_raw( $source['url'], array( 'https' ) ) : '';
				},
				$profile['sources']
			)
		)
	);
	if ( $citations ) {
		$data['citation'] = $citations;
	}
	return $data;
}
add_filter( 'wpseo_schema_article', 'tra_vel_v2_enrich_yoast_article_schema' );

/**
 * Identify directory pages as collections inside Yoast's graph.
 *
 * @param array<string, mixed> $data Yoast WebPage schema.
 * @return array<string, mixed>
 */
function tra_vel_v2_enrich_yoast_directory_schema( $data ) {
	if ( is_page_template( 'page-directory.php' ) ) {
		$data['@type']      = 'CollectionPage';
		$data['mainEntity'] = tra_vel_v2_directory_item_list();
	}
	return $data;
}
add_filter( 'wpseo_schema_webpage', 'tra_vel_v2_enrich_yoast_directory_schema' );
