<?php
/**
 * Search, canonical and structured-data policy for Tra-Vel V2.
 *
 * The graph identifies stable editorial entities and deliberately avoids demo
 * Product, Offer and FAQ markup. Live commercial schema belongs to verified
 * supplier data only.
 *
 * @package TraVelV2
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Keep reviewed guide canonicals independent from map/filter query strings.
 *
 * @param string  $canonical Canonical URL generated by WordPress.
 * @param WP_Post $post      Current post.
 * @return string
 */
function tra_vel_v2_canonical_guide_url( $canonical, $post ) {
	if ( $post instanceof WP_Post && tra_vel_v2_is_destination_guide( $post->ID ) ) {
		return get_permalink( $post->ID );
	}
	return $canonical;
}
add_filter( 'get_canonical_url', 'tra_vel_v2_canonical_guide_url', 10, 2 );

/**
 * Keep public titles destination-neutral and useful outside the former Europe focus.
 *
 * @param array<string, string> $parts Generated document title parts.
 * @return array<string, string>
 */
function tra_vel_v2_document_title_parts( $parts ) {
	$parts['site'] = 'Tra-Vel';

	if ( is_front_page() ) {
		$parts['title'] = __( 'חופשות, טיסות, מלונות ותכנון חכם', 'tra-vel-v2' );
	} elseif ( tra_vel_v2_is_destination_guide() ) {
		$parts['title'] = sprintf(
			/* translators: %s: destination name. */
			__( '%s | מדריך תכנון לישראלים', 'tra-vel-v2' ),
			get_the_title()
		);
	}

	return $parts;
}
add_filter( 'document_title_parts', 'tra_vel_v2_document_title_parts' );

/**
 * Return the public title used by SEO and social plugins that bypass core parts.
 *
 * @param string $title Existing generated title.
 * @return string
 */
function tra_vel_v2_public_seo_title( $title ) {
	if ( is_front_page() ) {
		return __( 'חופשות, טיסות, מלונות ותכנון חכם | Tra-Vel', 'tra-vel-v2' );
	}

	if ( tra_vel_v2_is_destination_guide() ) {
		return sprintf(
			/* translators: %s: destination name. */
			__( '%s | מדריך תכנון לישראלים | Tra-Vel', 'tra-vel-v2' ),
			get_the_title()
		);
	}

	return $title;
}
add_filter( 'wpseo_title', 'tra_vel_v2_public_seo_title' );
add_filter( 'wpseo_opengraph_title', 'tra_vel_v2_public_seo_title' );
add_filter( 'wpseo_twitter_title', 'tra_vel_v2_public_seo_title' );

/**
 * Remove the old Europe-only name from Yoast's WebSite entity.
 *
 * @param array<string, mixed> $data Yoast WebSite schema node.
 * @return array<string, mixed>
 */
function tra_vel_v2_enrich_yoast_website_schema( $data ) {
	$data['name']          = 'Tra-Vel';
	$data['alternateName'] = 'Tra-Vel';
	return $data;
}
add_filter( 'wpseo_schema_website', 'tra_vel_v2_enrich_yoast_website_schema' );

/**
 * Whether the current public request must remain outside the search index.
 *
 * Core and plugin robots emitters share this predicate so installing AIOSEO
 * cannot bypass the private-page, facet or incomplete-guide boundary.
 */
function tra_vel_v2_should_noindex_public_request() {
	$private_page = is_page_template( 'page-saved.php' ) || is_page_template( 'page-account.php' ) || is_page( array( 'saved', 'account' ) );
	$thin_archive = function_exists( 'is_author' ) && ( is_author() || is_category() || is_tag() || is_date() || is_search() );
	$incomplete_guide = is_singular() && tra_vel_v2_is_destination_guide() && ! tra_vel_v2_is_guide_publication_ready();
	$facet_keys   = array(
		'q', 'origin', 'destination', 'destination_mode', 'selection_destination', 'product', 'focus', 'layer', 'depart', 'departure', 'return', 'departure_date', 'return_date', 'date', 'dates', 'route', 'checkin', 'checkout', 'check_in', 'check_out', 'start_date', 'end_date', 'adults', 'children', 'infants', 'rooms', 'travelers', 'party',
		'currency', 'sort', 'stops', 'budget', 'hotel_class', 'amenities',
		'direct', 'trip', 'max_stops', 'max_duration', 'allow_overnight', 'flexible', 'flexibility', 'area', 'hotel_area', 'trip_destination', 'transfers', 'kosher', 'accessibility', 'vibe',
		'neighborhood', 'insurance', 'activities', 'scope', 'selection_id', 'selection_kind', 'latitude', 'longitude', 'map_lat', 'map_lng', 'map_zoom',
		'prompt', 'intent', 'mode', 'cabin', 'trip_style', 'insurance_tier',
	);
	$has_facets   = (bool) array_intersect( $facet_keys, array_keys( wp_unslash( $_GET ) ) ); // phpcs:ignore WordPress.Security.NonceVerification.Recommended

	return $private_page || $thin_archive || $has_facets || $incomplete_guide;
}

/**
 * Prevent personal pages and faceted map/search combinations becoming crawl traps.
 *
 * @param array<string, bool> $robots Existing directives.
 * @return array<string, bool>
 */
function tra_vel_v2_robots_policy( $robots ) {
	if ( tra_vel_v2_should_noindex_public_request() ) {
		$robots['noindex'] = true;
		$robots['follow']  = true;
		unset( $robots['index'], $robots['nofollow'] );
	}
	return $robots;
}
add_filter( 'wp_robots', 'tra_vel_v2_robots_policy' );

/** Preserve the same global noindex/follow policy when Yoast owns robots. */
function tra_vel_v2_yoast_robots_policy( $robots ) {
	if ( tra_vel_v2_should_noindex_public_request() ) {
		$robots['index'] = 'noindex';
		$robots['follow'] = 'follow';
	}
	return $robots;
}
add_filter( 'wpseo_robots_array', 'tra_vel_v2_yoast_robots_policy', 20 );

/** Preserve the same global noindex/follow policy when AIOSEO owns robots. */
function tra_vel_v2_aioseo_robots_policy( $attributes ) {
	if ( ! tra_vel_v2_should_noindex_public_request() ) {
		return $attributes;
	}

	$output = (array) $attributes;
	foreach ( (array) $attributes as $key => $value ) {
		$directive = is_string( $key ) ? strtolower( $key ) : strtolower( (string) $value );
		if ( in_array( $directive, array( 'index', 'nofollow' ), true ) ) {
			unset( $output[ $key ] );
		}
	}
	$output['noindex'] = 'noindex';
	$output['nofollow'] = '';
	return $output;
}
add_filter( 'aioseo_robots_meta', 'tra_vel_v2_aioseo_robots_policy', 20 );

/** Never guess-redirect unknown URLs into unrelated or unready pages; unlaunched paths must 404 cleanly. */
add_filter( 'do_redirect_guess_404_permalink', '__return_false' );

/** Keep author archives out of XML sitemaps; the byline system links authors internally instead. */
add_filter( 'wpseo_sitemap_exclude_author', '__return_true' );

/**
 * Keep thin taxonomy archives out of XML sitemaps until they carry curated content.
 *
 * @param bool   $excluded Current exclusion state.
 * @param string $taxonomy Taxonomy name.
 * @return bool
 */
function tra_vel_v2_sitemap_exclude_taxonomies( $excluded, $taxonomy ) {
	if ( in_array( (string) $taxonomy, array( 'category', 'post_tag', 'post_format' ), true ) ) {
		return true;
	}
	return (bool) $excluded;
}
add_filter( 'wpseo_sitemap_exclude_taxonomy', 'tra_vel_v2_sitemap_exclude_taxonomies', 10, 2 );

/**
 * Keep noindexed private pages and unready destination guides out of the page sitemap.
 *
 * @param array<int, int> $excluded_ids Post IDs Yoast already excludes.
 * @return array<int, int>
 */
function tra_vel_v2_sitemap_exclude_noindexed_pages( $excluded_ids ) {
	$excluded_ids = is_array( $excluded_ids ) ? $excluded_ids : array();
	foreach ( array( 'saved', 'account' ) as $private_slug ) {
		$private_page = get_page_by_path( $private_slug );
		if ( $private_page instanceof WP_Post ) {
			$excluded_ids[] = (int) $private_page->ID;
		}
	}
	$guide_pages = get_pages(
		array(
			'meta_key'   => '_wp_page_template',
			'meta_value' => 'page-destination.php',
			'number'     => 50,
		)
	);
	foreach ( (array) $guide_pages as $guide_page ) {
		if ( $guide_page instanceof WP_Post && function_exists( 'tra_vel_v2_is_guide_publication_ready' ) && ! tra_vel_v2_is_guide_publication_ready( $guide_page->ID ) ) {
			$excluded_ids[] = (int) $guide_page->ID;
		}
	}
	return array_values( array_unique( array_map( 'intval', $excluded_ids ) ) );
}
add_filter( 'wpseo_exclude_from_sitemap_by_post_ids', 'tra_vel_v2_sitemap_exclude_noindexed_pages' );

/**
 * Build a non-commercial ItemList for the editorial destination directory.
 *
 * Unreviewed destinations are represented as named places without public guide
 * URLs, preventing draft pages or noindex map facets from entering the graph.
 *
 * @return array<string, mixed>
 */
function tra_vel_v2_directory_item_list() {
	$path = TRA_VEL_V2_PATH . '/assets/data/editorial-directory.json';
	$data = file_exists( $path ) ? json_decode( file_get_contents( $path ), true ) : array();
	$earth_destinations = isset( $data['destinations'] ) && is_array( $data['destinations'] ) ? $data['destinations'] : array();
	$supporting_guides = isset( $data['supporting_guides'] ) && is_array( $data['supporting_guides'] ) ? $data['supporting_guides'] : array();
	$destinations = $earth_destinations;
	$is_guides_directory = is_page_template( 'page-directory.php' ) && 'guides' === get_post_field( 'post_name', get_queried_object_id() );
	if ( $is_guides_directory ) {
		$destinations = array_values(
			array_filter(
				array_merge( $earth_destinations, $supporting_guides ),
				static function ( $destination ) {
					return 'published' === ( $destination['guide_status'] ?? '' ) && ! empty( $destination['guide_path'] );
				}
			)
		);
	}
	$items = array();
	foreach ( $destinations as $index => $destination ) {
		$item = array(
			'@type'            => 'TouristDestination',
			'name'             => sanitize_text_field( $destination['city'] ?? '' ),
			'containedInPlace' => array(
				'@type' => 'Country',
				'name'  => sanitize_text_field( $destination['country'] ?? '' ),
			),
		);
		$guide_path = isset( $destination['guide_path'] ) ? (string) $destination['guide_path'] : '';
		if ( 'published' === ( $destination['guide_status'] ?? '' ) && tra_vel_v2_is_public_guide_path( $guide_path ) ) {
			$item['url'] = home_url( $guide_path );
		}
		$items[] = array(
			'@type'    => 'ListItem',
			'position' => $index + 1,
			'item'     => $item,
		);
	}
	return array(
		'@type'           => 'ItemList',
		'numberOfItems'   => count( $items ),
		'itemListElement' => $items,
	);
}

/**
 * Whether a reviewed guide path is provisionable by the destination template.
 *
 * One-level Earth guides and one additional supporting-guide level are public.
 * Deeper paths stay outside this phase of the contract.
 *
 * @param string $path Candidate site-relative path.
 * @return bool
 */
function tra_vel_v2_is_public_guide_path( $path ) {
	return (bool) preg_match( '#^/destinations/[a-z0-9-]+(?:/[a-z0-9-]+)?/$#', (string) $path );
}

/**
 * Build the Tra-Vel entity graph.
 *
 * @return array<string, mixed>
 */
function tra_vel_v2_schema_data() {
	$site_id = home_url( '/#website' );
	$org_id  = home_url( '/#organization' );
	$graph   = array(
		array(
			'@type'      => 'WebSite',
			'@id'        => $site_id,
			'url'        => home_url( '/' ),
			'name'       => get_bloginfo( 'name' ),
			'inLanguage' => 'he-IL',
			'publisher'  => array( '@id' => $org_id ),
		),
		array(
			'@type' => array( 'Organization', 'TravelAgency' ),
			'@id'   => $org_id,
			'name'  => 'Tra-Vel',
			'url'   => home_url( '/' ),
		),
	);

	if ( is_page_template( 'page-directory.php' ) ) {
		$url = get_permalink( get_queried_object_id() );
		$graph[] = array(
			'@type'      => 'CollectionPage',
			'@id'        => $url . '#webpage',
			'url'        => $url,
			'name'       => get_the_title(),
			'inLanguage' => 'he-IL',
			'isPartOf'   => array( '@id' => $site_id ),
			'mainEntity' => tra_vel_v2_directory_item_list(),
		);
		return array( '@context' => 'https://schema.org', '@graph' => $graph );
	}

	if ( is_page_template( 'page-seo-opportunity.php' ) && function_exists( 'tra_vel_v2_seo_opportunity_schema_nodes' ) ) {
		$opportunity_nodes = tra_vel_v2_seo_opportunity_schema_nodes( get_queried_object_id() );
		if ( $opportunity_nodes ) {
			$graph = array_merge( $graph, $opportunity_nodes );
		}
		return array( '@context' => 'https://schema.org', '@graph' => $graph );
	}

	if ( ! is_singular() || ! tra_vel_v2_is_destination_guide() ) {
		return array( '@context' => 'https://schema.org', '@graph' => $graph );
	}

	$post_id   = get_queried_object_id();
	$url       = get_permalink( $post_id );
	$profile   = tra_vel_v2_get_guide_profile( $post_id );
	$webpage   = array(
		'@type'      => 'WebPage',
		'@id'        => $url . '#webpage',
		'url'        => $url,
		'name'       => get_the_title( $post_id ),
		'inLanguage' => 'he-IL',
		'isPartOf'   => array( '@id' => $site_id ),
		'breadcrumb' => array( '@id' => $url . '#breadcrumb' ),
	);
	$breadcrumb_items = array();
	foreach ( tra_vel_v2_guide_breadcrumb_items( $post_id ) as $position => $item ) {
		$breadcrumb_items[] = array(
			'@type'    => 'ListItem',
			'position' => $position + 1,
			'name'     => $item['name'],
			'item'     => $item['url'],
		);
	}
	$breadcrumb = array(
		'@type'           => 'BreadcrumbList',
		'@id'             => $url . '#breadcrumb',
		'itemListElement' => $breadcrumb_items,
	);

	if ( ! tra_vel_v2_is_guide_publication_ready( $post_id ) ) {
		$graph[] = $webpage;
		$graph[] = $breadcrumb;
		return array( '@context' => 'https://schema.org', '@graph' => $graph );
	}

	$author_id = (int) get_post_field( 'post_author', $post_id );
	$author    = $profile['author'] ?: ( get_the_author_meta( 'display_name', $author_id ) ?: 'Tra-Vel' );
	$author_type = false !== stripos( $author, 'Tra-Vel' ) ? 'Organization' : 'Person';
	$image     = get_the_post_thumbnail_url( $post_id, 'full' );
	$excerpt   = get_the_excerpt( $post_id );
	$article   = array(
		'@type'            => 'Article',
		'@id'              => $url . '#guide',
		'url'              => $url,
		'headline'         => get_the_title( $post_id ),
		'description'      => $excerpt ? wp_strip_all_tags( $excerpt ) : wp_trim_words( wp_strip_all_tags( get_post_field( 'post_content', $post_id ) ), 34 ),
		'datePublished'    => get_the_date( DATE_W3C, $post_id ),
		'dateModified'     => get_the_modified_date( DATE_W3C, $post_id ),
		'inLanguage'       => 'he-IL',
		'mainEntityOfPage' => array( '@id' => $url . '#webpage' ),
		'isPartOf'         => array( '@id' => $site_id ),
		'author'           => array( '@type' => $author_type, 'name' => $author ),
		'publisher'        => array( '@id' => $org_id ),
	);

	if ( $image ) {
		$article['image'] = esc_url_raw( $image );
	}
	if ( $profile['primary_topic'] ) {
		$article['about'] = array( '@type' => 'TouristDestination', 'name' => get_the_title( $post_id ) );
	}
	if ( $profile['is_reviewed'] ) {
		$article['lastReviewed'] = $profile['checked'];
	}

	$citations = array_values(
		array_filter(
			array_map(
				static function ( $source ) {
					return ! empty( $source['url'] ) ? esc_url_raw( $source['url'], array( 'https' ) ) : '';
				},
				$profile['sources']
			)
		)
	);
	if ( $citations ) {
		$article['citation'] = $citations;
	}

	$webpage['about'] = array( '@id' => $url . '#guide' );
	$graph[] = $webpage;
	$graph[] = $article;
	$graph[] = $breadcrumb;

	return array( '@context' => 'https://schema.org', '@graph' => $graph );
}

/** Print the JSON-LD graph. */
function tra_vel_v2_schema_graph() {
	if ( is_admin() || is_feed() ) {
		return;
	}
	if ( defined( 'WPSEO_VERSION' ) || defined( 'AIOSEO_VERSION' ) || function_exists( 'aioseo' ) ) {
		// The active SEO plugin owns the graph. Filters below enrich or gate it.
		return;
	}
	echo '<script type="application/ld+json">' . wp_json_encode( tra_vel_v2_schema_data(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE ) . '</script>';
}
add_action( 'wp_head', 'tra_vel_v2_schema_graph', 20 );

/**
 * Enrich Yoast's canonical Article node instead of printing a duplicate graph.
 *
 * @param array<string, mixed> $data Yoast Article schema.
 * @return array<string, mixed>
 */
function tra_vel_v2_enrich_yoast_article_schema( $data ) {
	if ( ! tra_vel_v2_is_destination_guide() ) {
		return $data;
	}
	if ( ! tra_vel_v2_is_guide_publication_ready() ) {
		return $data;
	}
	$profile = tra_vel_v2_get_guide_profile();
	if ( $profile['primary_topic'] ) {
		$data['about'] = array( '@type' => 'TouristDestination', 'name' => get_the_title( get_queried_object_id() ) );
	}
	if ( $profile['is_reviewed'] ) {
		$data['lastReviewed'] = $profile['checked'];
	}
	$citations = array_values(
		array_filter(
			array_map(
				static function ( $source ) {
					return ! empty( $source['url'] ) ? esc_url_raw( $source['url'], array( 'https' ) ) : '';
				},
				$profile['sources']
			)
		)
	);
	if ( $citations ) {
		$data['citation'] = $citations;
	}
	return $data;
}
add_filter( 'wpseo_schema_article', 'tra_vel_v2_enrich_yoast_article_schema' );

/**
 * Remove Yoast's Article graph piece until the guide publication gate passes.
 *
 * @param array<int, object> $pieces  Yoast graph-piece objects.
 * @param mixed              $context Yoast schema context.
 * @return array<int, object>
 */
function tra_vel_v2_gate_yoast_article_piece( $pieces, $context = null ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed
	if ( ! tra_vel_v2_is_destination_guide() || tra_vel_v2_is_guide_publication_ready() ) {
		return $pieces;
	}

	return array_values(
		array_filter(
			$pieces,
			static function ( $piece ) {
				return ! is_a( $piece, '\\Yoast\\WP\\SEO\\Generators\\Schema\\Article' );
			}
		)
	);
}
add_filter( 'wpseo_schema_graph_pieces', 'tra_vel_v2_gate_yoast_article_piece', 11, 2 );

/**
 * Enrich a complete AIOSEO Article and remove Article claims from thin guides.
 *
 * @param array<int, array<string, mixed>> $schema AIOSEO graph nodes.
 * @return array<int, array<string, mixed>>
 */
function tra_vel_v2_gate_aioseo_guide_schema( $schema ) {
	if ( ! tra_vel_v2_is_destination_guide() || ! is_array( $schema ) ) {
		return $schema;
	}

	$ready   = tra_vel_v2_is_guide_publication_ready();
	$profile = $ready ? tra_vel_v2_get_guide_profile() : array();
	$output  = array();
	foreach ( $schema as $node ) {
		if ( ! is_array( $node ) ) {
			$output[] = $node;
			continue;
		}
		$types = isset( $node['@type'] ) ? (array) $node['@type'] : array();
		$is_article = (bool) array_intersect( array( 'Article', 'BlogPosting', 'NewsArticle' ), $types );
		if ( ! $ready && $is_article ) {
			continue;
		}
		if ( ! $ready && in_array( 'WebPage', $types, true ) ) {
			unset( $node['about'], $node['mainEntity'] );
		}
		if ( $ready && $is_article ) {
			$node['about']        = array( '@type' => 'TouristDestination', 'name' => get_the_title( get_queried_object_id() ) );
			$node['lastReviewed'] = $profile['checked'];
			$node['citation']     = array_values(
				array_filter(
					array_map(
						static function ( $source ) {
							return ! empty( $source['url'] ) ? esc_url_raw( $source['url'], array( 'https' ) ) : '';
						},
						$profile['sources']
					)
				)
			);
		}
		$output[] = $node;
	}

	return array_values( $output );
}
add_filter( 'aioseo_schema_output', 'tra_vel_v2_gate_aioseo_guide_schema' );

/**
 * Identify directory pages as collections inside Yoast's graph.
 *
 * @param array<string, mixed> $data Yoast WebPage schema.
 * @return array<string, mixed>
 */
function tra_vel_v2_enrich_yoast_directory_schema( $data ) {
	if ( is_page_template( 'page-directory.php' ) ) {
		$data['@type']      = 'CollectionPage';
		$data['mainEntity'] = tra_vel_v2_directory_item_list();
	} elseif ( tra_vel_v2_is_destination_guide() && ! tra_vel_v2_is_guide_publication_ready() ) {
		unset( $data['about'], $data['mainEntity'] );
	}
	return $data;
}
add_filter( 'wpseo_schema_webpage', 'tra_vel_v2_enrich_yoast_directory_schema' );
