<?php
/**
 * Server-only provider of normalized, authoritative Trip Cockpit components.
 *
 * Implementations assemble current customer-safe projections from durable
 * registration, servicing, commerce, Trip Care, loyalty, and offline-pack
 * repositories. They must never accept a browser-provided source bundle.
 *
 * @package TraVelAgent
 */

defined( 'ABSPATH' ) || exit;

interface Tra_Vel_Customer_Trip_Cockpit_Source_Provider {
	/**
	 * Return the exact current component snapshot for one owner-bound trip.
	 *
	 * The context is generated by the source assembler and contains only
	 * event_ref, event_kind, owner_user_id, account_ref, and trip_ref.
	 *
	 * @param array $context Closed server-generated lifecycle context.
	 * @return array|WP_Error|null Null means that no authoritative snapshot is available yet.
	 */
	public function get_authoritative_snapshot( $context );
}
