<?php
/**
 * Tra-Vel V2 commercial discovery homepage.
 *
 * @package TraVelV2
 */

get_header();
$map_url       = home_url( '/travel-map/' );
$thailand_url  = home_url( '/destinations/thailand/' );
$planner_url   = home_url( '/ai-planner/' );
$surprise_url  = add_query_arg( 'mode', 'surprise', $planner_url );
$hero_campaign = tra_vel_v2_get_home_hero_campaign();
$home_now       = current_datetime();
$home_today     = $home_now->format( 'Y-m-d' );
$home_departure = $home_now->modify( '+30 days' )->format( 'Y-m-d' );
$home_return    = $home_now->modify( '+34 days' )->format( 'Y-m-d' );
?>
<main id="main-content">
	<section class="home-hero">
		<div class="hero-grid page-width">
			<div class="hero-copy">
				<span class="kicker"><i data-lucide="sparkles"></i><?php esc_html_e( 'Tra-Vel Intelligence · מסע אחד, החלטה אחת בכל פעם', 'tra-vel-v2' ); ?></span>
				<h1><?php esc_html_e( 'כל העולם.', 'tra-vel-v2' ); ?><br><em><?php esc_html_e( 'על מפה אחת.', 'tra-vel-v2' ); ?></em></h1>
				<p><?php esc_html_e( 'בוחרים מקום על הגלובוס ומקבלים טיסות, מלונות, מסלולים, ביטוח ועלות אמיתית, עם הסבר מה עדיף ולמה.', 'tra-vel-v2' ); ?></p>
				<div class="hero-agent-actions">
					<a class="ai-prompt" href="<?php echo esc_url( $planner_url ); ?>"><i data-lucide="bot"></i><span><?php esc_html_e( 'אפשר גם לכתוב:', 'tra-vel-v2' ); ?></span><strong><?php esc_html_e( '“שבועיים בתאילנד עד ₪9,000 לזוג”', 'tra-vel-v2' ); ?></strong><i data-lucide="arrow-left"></i></a>
					<a class="surprise-cta" href="<?php echo esc_url( $surprise_url ); ?>"><i data-lucide="dices"></i><span><strong><?php esc_html_e( 'תפתיעו אותי', 'tra-vel-v2' ); ?></strong><small><?php esc_html_e( 'אתם מספרים תקציב ואווירה. הסוכן מתחיל לבנות בקשה.', 'tra-vel-v2' ); ?></small></span><i data-lucide="arrow-left"></i></a>
				</div>
				<?php if ( $hero_campaign ) : ?>
					<aside class="hero-campaign" data-hero-campaign="<?php echo esc_attr( $hero_campaign['id'] ); ?>" data-map-state="<?php echo esc_attr( $hero_campaign['map_state'] ); ?>">
						<div class="hero-campaign-heading"><span><i data-lucide="calendar-heart"></i><?php echo esc_html( $hero_campaign['eyebrow'] ); ?></span><small><?php esc_html_e( 'בחירה עונתית', 'tra-vel-v2' ); ?></small></div>
						<strong><?php echo esc_html( $hero_campaign['title'] ); ?></strong>
						<p><?php echo esc_html( $hero_campaign['copy'] ); ?></p>
						<div class="hero-campaign-actions"><a class="is-primary" href="<?php echo esc_url( home_url( $hero_campaign['primary_url'] ) ); ?>"><?php echo esc_html( $hero_campaign['primary_label'] ); ?><i data-lucide="arrow-left"></i></a><a href="<?php echo esc_url( home_url( $hero_campaign['secondary_url'] ) ); ?>"><?php echo esc_html( $hero_campaign['secondary_label'] ); ?></a></div>
					</aside>
				<?php endif; ?>
			</div>
			<div class="home-globe-stack">
			<div class="globe-panel" aria-label="<?php esc_attr_e( 'מפת יעדים אינטראקטיבית', 'tra-vel-v2' ); ?>">
				<div class="globe-halo"></div>
				<div class="globe" data-discovery-globe>
					<span class="origin-point" title="<?php esc_attr_e( 'תל אביב', 'tra-vel-v2' ); ?>"></span>
					<span class="route-curve curve-one"></span><span class="route-curve curve-two"></span>
					<button class="price-pin pin-budapest" data-destination="budapest" type="button">BUD</button>
					<button class="price-pin pin-athens" data-destination="athens" type="button">ATH</button>
					<button class="price-pin pin-dubai" data-destination="dubai" type="button">DXB</button>
					<button class="price-pin pin-bangkok is-active" data-destination="bangkok" type="button">BKK</button>
					<button class="price-pin pin-tokyo" data-destination="tokyo" type="button">TYO</button>
					<button class="price-pin pin-lisbon" data-destination="lisbon" type="button">LIS</button>
				</div>
				<div class="globe-tools"><button data-map-zoom="in" type="button" aria-label="<?php esc_attr_e( 'הגדלה', 'tra-vel-v2' ); ?>"><i data-lucide="plus"></i></button><button data-map-zoom="out" type="button" aria-label="<?php esc_attr_e( 'הקטנה', 'tra-vel-v2' ); ?>"><i data-lucide="minus"></i></button><a href="<?php echo esc_url( $map_url ); ?>" aria-label="<?php esc_attr_e( 'מפה מלאה', 'tra-vel-v2' ); ?>"><i data-lucide="maximize-2"></i></a></div>
			</div>
				<article class="map-result" data-map-result>
					<img class="map-result-image" data-result-image src="<?php echo tra_vel_v2_asset_uri( 'images/thailand.jpg' ); ?>" alt="<?php esc_attr_e( 'בנגקוק, תאילנד', 'tra-vel-v2' ); ?>">
					<div class="map-result-body"><div class="result-top"><div><small><?php esc_html_e( 'הבחירה שנבדקת עכשיו', 'tra-vel-v2' ); ?></small><h3 data-result-city><?php esc_html_e( 'בנגקוק, תאילנד', 'tra-vel-v2' ); ?></h3></div><button class="save-button" type="button" aria-label="<?php esc_attr_e( 'שמירה', 'tra-vel-v2' ); ?>"><i data-lucide="heart"></i></button></div><div class="result-tags" data-result-tags><span><?php esc_html_e( '12 לילות', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'עצירה אחת', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'בדיקת כבודה', 'tra-vel-v2' ); ?></span></div><div class="result-price"><div><small><?php esc_html_e( 'מחיר ותנאים', 'tra-vel-v2' ); ?></small><strong data-result-price><?php esc_html_e( 'בדיקה חיה', 'tra-vel-v2' ); ?></strong></div><p data-result-note><?php esc_html_e( 'המחיר יופיע לאחר בחירת תאריכים והרכב.', 'tra-vel-v2' ); ?></p></div><div class="home-plan-360" data-home-plan aria-busy="false"><div><span>Tra-Vel 360°</span><strong data-home-plan-summary role="status" aria-live="polite"><?php esc_html_e( 'בנגקוק נבחרה. עכשיו מחברים דרך, לינה, חוויות והגנה.', 'tra-vel-v2' ); ?></strong></div><nav aria-label="<?php esc_attr_e( 'אפשרויות לתכנון היעד', 'tra-vel-v2' ); ?>"><a data-home-plan-flight href="<?php echo esc_url( home_url( '/flights/?destination=BKK' ) ); ?>"><i data-lucide="plane-takeoff"></i><?php esc_html_e( 'דרך', 'tra-vel-v2' ); ?></a><a data-home-plan-stay href="<?php echo esc_url( home_url( '/hotels/?destination=BKK' ) ); ?>"><i data-lucide="hotel"></i><?php esc_html_e( 'לינה', 'tra-vel-v2' ); ?></a><a data-home-plan-guide href="<?php echo esc_url( $thailand_url ); ?>"><i data-lucide="map"></i><?php esc_html_e( 'מה עושים', 'tra-vel-v2' ); ?></a><a data-home-plan-ai href="<?php echo esc_url( add_query_arg( 'destination', 'bangkok', $planner_url ) ); ?>"><i data-lucide="sparkles"></i><?php esc_html_e( 'סוכן AI', 'tra-vel-v2' ); ?></a></nav><a class="home-plan-full" data-home-plan-full href="<?php echo esc_url( add_query_arg( 'destination', 'bangkok', $map_url ) ); ?>"><?php esc_html_e( 'פתחו תוכנית 360° מלאה', 'tra-vel-v2' ); ?><i data-lucide="arrow-left"></i></a></div></div>
				</article>
				<?php tra_vel_v2_demo_disclosure(); ?>
			</div>
		</div>
	</section>

	<section class="search-zone" id="search">
		<div class="page-width">
			<noscript>
				<style>.search-zone .product-tabs,.search-zone .search-dock,.search-zone .home-search-progress{display:none!important}</style>
				<nav class="product-links-noscript" aria-label="<?php esc_attr_e( 'פתיחת השוואה ללא JavaScript', 'tra-vel-v2' ); ?>"><p><?php esc_html_e( 'בחרו עמוד השוואה והשלימו בו את פרטי הנסיעה.', 'tra-vel-v2' ); ?></p><a href="<?php echo esc_url( home_url( '/packages/' ) ); ?>"><?php esc_html_e( 'טיסה ומלון', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( home_url( '/flights/' ) ); ?>"><?php esc_html_e( 'טיסות', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( home_url( '/hotels/' ) ); ?>"><?php esc_html_e( 'מלונות', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( home_url( '/travel-insurance/' ) ); ?>"><?php esc_html_e( 'ביטוח', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( $map_url ); ?>"><?php esc_html_e( 'מפת היעדים', 'tra-vel-v2' ); ?></a></nav>
			</noscript>
			<div class="product-tabs" role="tablist" aria-label="<?php esc_attr_e( 'סוג חיפוש', 'tra-vel-v2' ); ?>" aria-orientation="horizontal">
				<button id="home-search-tab-package" class="is-active" type="button" role="tab" aria-selected="true" aria-controls="home-search-panel" tabindex="0" data-product-kind="package" data-product-action="<?php echo esc_url( home_url( '/packages/' ) ); ?>" data-submit-label="<?php esc_attr_e( 'בנו והשוו נסיעה', 'tra-vel-v2' ); ?>" data-departure-label="<?php esc_attr_e( 'יציאה', 'tra-vel-v2' ); ?>" data-return-label="<?php esc_attr_e( 'חזרה', 'tra-vel-v2' ); ?>"><i data-lucide="package"></i><?php esc_html_e( 'טיסה + מלון', 'tra-vel-v2' ); ?></button>
				<button id="home-search-tab-flights" type="button" role="tab" aria-selected="false" aria-controls="home-search-panel" tabindex="-1" data-product-kind="flights" data-product-action="<?php echo esc_url( home_url( '/flights/' ) ); ?>" data-submit-label="<?php esc_attr_e( 'השוו טיסות', 'tra-vel-v2' ); ?>" data-departure-label="<?php esc_attr_e( 'יציאה', 'tra-vel-v2' ); ?>" data-return-label="<?php esc_attr_e( 'חזרה', 'tra-vel-v2' ); ?>"><i data-lucide="plane"></i><?php esc_html_e( 'טיסות', 'tra-vel-v2' ); ?></button>
				<button id="home-search-tab-hotels" type="button" role="tab" aria-selected="false" aria-controls="home-search-panel" tabindex="-1" data-product-kind="hotels" data-product-action="<?php echo esc_url( home_url( '/hotels/' ) ); ?>" data-submit-label="<?php esc_attr_e( 'השוו מלונות', 'tra-vel-v2' ); ?>" data-departure-label="<?php esc_attr_e( 'כניסה', 'tra-vel-v2' ); ?>" data-return-label="<?php esc_attr_e( 'יציאה', 'tra-vel-v2' ); ?>"><i data-lucide="hotel"></i><?php esc_html_e( 'מלונות', 'tra-vel-v2' ); ?></button>
				<button id="home-search-tab-packages" type="button" role="tab" aria-selected="false" aria-controls="home-search-panel" tabindex="-1" data-product-kind="packages" data-product-action="<?php echo esc_url( home_url( '/packages/' ) ); ?>" data-submit-label="<?php esc_attr_e( 'הרכיבו חבילה', 'tra-vel-v2' ); ?>" data-departure-label="<?php esc_attr_e( 'יציאה', 'tra-vel-v2' ); ?>" data-return-label="<?php esc_attr_e( 'חזרה', 'tra-vel-v2' ); ?>"><i data-lucide="palmtree"></i><?php esc_html_e( 'חבילות', 'tra-vel-v2' ); ?></button>
				<button id="home-search-tab-insurance" type="button" role="tab" aria-selected="false" aria-controls="home-search-panel" tabindex="-1" data-product-kind="insurance" data-product-action="<?php echo esc_url( home_url( '/travel-insurance/' ) ); ?>" data-submit-label="<?php esc_attr_e( 'השוו כיסוי', 'tra-vel-v2' ); ?>" data-departure-label="<?php esc_attr_e( 'תחילת כיסוי', 'tra-vel-v2' ); ?>" data-return-label="<?php esc_attr_e( 'סיום כיסוי', 'tra-vel-v2' ); ?>"><i data-lucide="shield-check"></i><?php esc_html_e( 'ביטוח', 'tra-vel-v2' ); ?></button>
			</div>
			<form id="home-search-panel" class="search-dock" action="<?php echo esc_url( $map_url ); ?>" method="get" role="tabpanel" aria-labelledby="home-search-tab-package" aria-describedby="home-search-status" aria-busy="false" data-home-search data-product-kind="package" data-map-action="<?php echo esc_url( $map_url ); ?>" data-state="ready" data-uses-origin="true" data-uses-rooms="true">
				<fieldset class="search-field search-route-field">
					<legend><i data-lucide="map-pin" aria-hidden="true"></i><?php esc_html_e( 'מאיפה ולאן', 'tra-vel-v2' ); ?></legend>
					<div class="search-field-controls">
						<label data-home-origin-wrap><span><?php esc_html_e( 'יציאה מ', 'tra-vel-v2' ); ?></span><input name="origin" value="TLV" maxlength="3" pattern="[A-Za-z]{3}" inputmode="text" autocomplete="off" aria-label="<?php esc_attr_e( 'קוד שדה תעופה מוצא', 'tra-vel-v2' ); ?>" required></label>
						<i data-lucide="arrow-left" aria-hidden="true"></i>
						<label><span><?php esc_html_e( 'יעד', 'tra-vel-v2' ); ?></span><select name="destination" data-home-destination aria-label="<?php esc_attr_e( 'בחירת יעד', 'tra-vel-v2' ); ?>"><option value="anywhere" data-code="anywhere" data-slug="anywhere"><?php esc_html_e( 'לא משנה לאן', 'tra-vel-v2' ); ?></option><option value="BUD" data-code="BUD" data-slug="budapest"><?php esc_html_e( 'בודפשט', 'tra-vel-v2' ); ?> · BUD</option><option value="ATH" data-code="ATH" data-slug="athens"><?php esc_html_e( 'אתונה', 'tra-vel-v2' ); ?> · ATH</option><option value="DXB" data-code="DXB" data-slug="dubai"><?php esc_html_e( 'דובאי', 'tra-vel-v2' ); ?> · DXB</option><option value="BKK" data-code="BKK" data-slug="bangkok"><?php esc_html_e( 'בנגקוק', 'tra-vel-v2' ); ?> · BKK</option><option value="HND" data-code="HND" data-slug="tokyo"><?php esc_html_e( 'טוקיו', 'tra-vel-v2' ); ?> · HND</option><option value="LIS" data-code="LIS" data-slug="lisbon"><?php esc_html_e( 'ליסבון', 'tra-vel-v2' ); ?> · LIS</option></select></label>
					</div>
				</fieldset>
				<fieldset class="search-field search-date-field">
					<legend><i data-lucide="calendar-range" aria-hidden="true"></i><?php esc_html_e( 'מתי', 'tra-vel-v2' ); ?></legend>
					<div class="search-field-controls search-date-controls"><label><span data-home-departure-label><?php esc_html_e( 'יציאה', 'tra-vel-v2' ); ?></span><input type="date" name="departure_date" min="<?php echo esc_attr( $home_today ); ?>" value="<?php echo esc_attr( $home_departure ); ?>" data-home-departure required></label><label><span data-home-return-label><?php esc_html_e( 'חזרה', 'tra-vel-v2' ); ?></span><input type="date" name="return_date" min="<?php echo esc_attr( $home_now->modify( '+31 days' )->format( 'Y-m-d' ) ); ?>" value="<?php echo esc_attr( $home_return ); ?>" data-home-return required></label></div>
				</fieldset>
				<fieldset class="search-field search-traveler-field">
					<legend><i data-lucide="users" aria-hidden="true"></i><?php esc_html_e( 'מי נוסע', 'tra-vel-v2' ); ?></legend>
					<div class="search-field-controls"><label><span><?php esc_html_e( 'מבוגרים', 'tra-vel-v2' ); ?></span><select name="adults" data-home-adults><option value="1">1</option><option value="2" selected>2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option></select></label><label><span><?php esc_html_e( 'ילדים', 'tra-vel-v2' ); ?></span><select name="children" data-home-children><option value="0" selected>0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label><label data-home-rooms-wrap><span><?php esc_html_e( 'חדרים', 'tra-vel-v2' ); ?></span><select name="rooms" data-home-rooms><option value="1" selected>1</option><option value="2">2</option><option value="3">3</option></select></label></div>
				</fieldset>
				<button class="search-submit" type="submit" data-home-search-submit><i data-lucide="search"></i><span><?php esc_html_e( 'בנו והשוו נסיעה', 'tra-vel-v2' ); ?></span></button>
			</form>
			<div class="home-search-progress" data-home-search-progress data-state="ready">
				<ol aria-label="<?php esc_attr_e( 'התקדמות החיפוש', 'tra-vel-v2' ); ?>"><li data-home-search-step="product" data-state="confirmed"><i data-lucide="layout-list" aria-hidden="true"></i><span><b><?php esc_html_e( 'סוג השוואה', 'tra-vel-v2' ); ?></b><small><?php esc_html_e( 'טיסה ומלון נבחרו', 'tra-vel-v2' ); ?></small></span></li><li data-home-search-step="criteria" data-state="confirmed"><i data-lucide="list-checks" aria-hidden="true"></i><span><b><?php esc_html_e( 'פרטי נסיעה', 'tra-vel-v2' ); ?></b><small><?php esc_html_e( 'הפרטים מוכנים', 'tra-vel-v2' ); ?></small></span></li><li data-home-search-step="handoff" data-state="waiting"><i data-lucide="scan-search" aria-hidden="true"></i><span><b><?php esc_html_e( 'השוואה עדכנית', 'tra-vel-v2' ); ?></b><small><?php esc_html_e( 'תתחיל לאחר לחיצה', 'tra-vel-v2' ); ?></small></span></li></ol>
				<p id="home-search-status" data-home-search-status role="status" aria-live="polite" aria-atomic="true"><?php esc_html_e( 'הפרטים מוכנים. המחירים והזמינות ייבדקו בעמוד ההשוואה.', 'tra-vel-v2' ); ?></p>
			</div>
			<div class="quick-links"><span><?php esc_html_e( 'רעיונות מהירים:', 'tra-vel-v2' ); ?></span><a href="<?php echo esc_url( add_query_arg( 'budget', '950', $map_url ) ); ?>"><?php esc_html_e( 'עד $950 לאדם', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( add_query_arg( 'direct', '1', $map_url ) ); ?>"><?php esc_html_e( 'טיסות ישירות', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( add_query_arg( 'intent', 'family', $map_url ) ); ?>"><?php esc_html_e( 'עם ילדים', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( $map_url ); ?>"><?php esc_html_e( 'לא משנה לאן', 'tra-vel-v2' ); ?></a></div>
			<div class="intelligence-strip"><div><span class="strip-icon"><i data-lucide="trending-down"></i></span><span><small><?php esc_html_e( 'מחיר טוב באמת', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'ייבדק מול חלופות עדכניות', 'tra-vel-v2' ); ?></strong></span></div><div><span class="strip-icon"><i data-lucide="calculator"></i></span><span><small><?php esc_html_e( 'עלות כוללת', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'בודקים כבודה, העברות וביטוח', 'tra-vel-v2' ); ?></strong></span></div><div><span class="strip-icon"><i data-lucide="route"></i></span><span><small><?php esc_html_e( 'מסלולים חכמים', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'ישיר, קונקשן ותחנות בדרך', 'tra-vel-v2' ); ?></strong></span></div><div><span class="strip-icon"><i data-lucide="badge-check"></i></span><span><small><?php esc_html_e( 'למה זה מתאים', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'יתרונות, חסרונות ורמת סיכון', 'tra-vel-v2' ); ?></strong></span></div></div>
		</div>
	</section>

	<section class="section" id="routes"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'אותו יעד, שלוש החלטות שונות', 'tra-vel-v2' ); ?></span><h2 data-route-title><?php esc_html_e( 'מהי הדרך החכמה לבנגקוק?', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'אנחנו לא בוחרים רק את הזול. אנחנו מסבירים את המחיר של כל בחירה בזמן, נוחות וגמישות.', 'tra-vel-v2' ); ?></p></div><a class="text-link" href="<?php echo esc_url( $map_url ); ?>"><?php esc_html_e( 'השוואה מלאה במפה', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></div>
		<p class="route-empty" data-home-route-empty hidden><?php esc_html_e( 'ליעד הזה עדיין אין השוואת מסלולים מלאה בעמוד הבית. פתחו את המפה כדי לבנות תוכנית 360° מעודכנת.', 'tra-vel-v2' ); ?></p>
		<div class="route-board" data-home-route-board><header class="route-board-head"><div class="route-airports"><b class="airport-code">TLV</b><span><i data-lucide="plane"></i></span><b class="airport-code">BKK</b><small><?php esc_html_e( 'תאריכים גמישים · 2 נוסעים', 'tra-vel-v2' ); ?></small></div><span class="updated"><?php esc_html_e( 'מחירים ותנאים יאומתו בחיפוש חי', 'tra-vel-v2' ); ?></span></header><div class="route-cards">
			<button class="route-card" type="button" data-route data-route-summary="<?php esc_attr_e( 'ישיר: הבחירה הנוחה ביותר כאשר המחיר מתאים', 'tra-vel-v2' ); ?>"><div class="route-card-top"><span class="route-badge"><?php esc_html_e( 'הכי נוח', 'tra-vel-v2' ); ?></span><strong class="price"><?php esc_html_e( 'בדיקה חיה', 'tra-vel-v2' ); ?></strong></div><h3><?php esc_html_e( 'מסלול ישיר', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'ללא החלפה · לפי זמינות', 'tra-vel-v2' ); ?></p><div class="route-data"><span><i data-lucide="clock-3"></i><?php esc_html_e( 'הזמן הקצר', 'tra-vel-v2' ); ?></span><span><i data-lucide="briefcase"></i><?php esc_html_e( 'בדיקת כבודה', 'tra-vel-v2' ); ?></span><span><i data-lucide="shield"></i><?php esc_html_e( 'סיכון נמוך', 'tra-vel-v2' ); ?></span></div></button>
			<button class="route-card recommended is-selected" type="button" data-route data-route-summary="<?php esc_attr_e( 'קונקשן בכרטיס אחד: איזון אפשרי בין מחיר, זמן ופשטות', 'tra-vel-v2' ); ?>"><div class="route-card-top"><span class="route-badge"><?php esc_html_e( 'מאוזן', 'tra-vel-v2' ); ?></span><strong class="price"><?php esc_html_e( 'דורש בדיקה', 'tra-vel-v2' ); ?></strong></div><h3><?php esc_html_e( 'קונקשן בכרטיס אחד', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'עצירה אחת · תנאים ייבדקו', 'tra-vel-v2' ); ?></p><div class="route-data"><span><i data-lucide="piggy-bank"></i><?php esc_html_e( 'בדיקת מחיר', 'tra-vel-v2' ); ?></span><span><i data-lucide="coffee"></i><?php esc_html_e( 'משך העצירה', 'tra-vel-v2' ); ?></span><span><i data-lucide="ticket-check"></i><?php esc_html_e( 'כרטיס אחד', 'tra-vel-v2' ); ?></span></div></button>
			<button class="route-card" type="button" data-route data-route-summary="<?php esc_attr_e( 'עצירת לילה: יותר גמישות עם אחריות מעבר גבוהה יותר', 'tra-vel-v2' ); ?>"><div class="route-card-top"><span class="route-badge"><?php esc_html_e( 'גמיש', 'tra-vel-v2' ); ?></span><strong class="price"><?php esc_html_e( 'בדיקת סיכון', 'tra-vel-v2' ); ?></strong></div><h3><?php esc_html_e( 'עצירת לילה בדרך', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'כרטיסים נפרדים · זמן נוסף', 'tra-vel-v2' ); ?></p><div class="route-data"><span><i data-lucide="badge-dollar-sign"></i><?php esc_html_e( 'עלות מלאה', 'tra-vel-v2' ); ?></span><span><i data-lucide="bed-double"></i><?php esc_html_e( 'לילה בדרך', 'tra-vel-v2' ); ?></span><span><i data-lucide="triangle-alert"></i><?php esc_html_e( 'סיכון גבוה יותר', 'tra-vel-v2' ); ?></span></div></button>
		</div><p class="updated" data-route-summary><?php esc_html_e( 'קונקשן בכרטיס אחד: איזון אפשרי בין מחיר, זמן ופשטות', 'tra-vel-v2' ); ?></p></div></div></section>

	<section class="section soft" id="deals"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'הזדמנויות עם תנאים ברורים', 'tra-vel-v2' ); ?></span><h2><?php esc_html_e( 'רעיונות שכדאי לבדוק עכשיו', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'כל אפשרות מקבלת הקשר: מה צריך לכלול, מול מה להשוות ואילו תנאים לבדוק.', 'tra-vel-v2' ); ?></p></div><a class="text-link" href="<?php echo esc_url( $map_url ); ?>"><?php esc_html_e( 'כל האפשרויות על המפה', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></div><div class="deal-grid">
		<?php
		$deals = array(
			array( 'image' => 'city-budapest.webp', 'tag' => 'עירוני', 'meta' => 'בודפשט · 4 לילות · מרכז העיר', 'title' => 'סוף שבוע עם מסלול גמיש', 'price' => 'בדיקה חיה' ),
			array( 'image' => 'thailand.jpg', 'tag' => 'טיסה + מלון', 'meta' => 'תאילנד · 10 לילות · לפי העונה', 'title' => 'איים, ספא וביטול גמיש', 'price' => 'בדיקה חיה' ),
			array( 'image' => 'city-vienna.webp', 'tag' => 'עיר ותרבות', 'meta' => 'וינה · 3 לילות · אזור נוח', 'title' => 'תרבות, אוכל ותחבורה יעילה', 'price' => 'בדיקה חיה' ),
		);
		foreach ( $deals as $deal ) :
			?>
			<article class="deal-card"><div class="deal-media" style="background-image:url('<?php echo tra_vel_v2_asset_uri( 'images/' . $deal['image'] ); ?>')"><span class="deal-tag"><?php echo esc_html( $deal['tag'] ); ?></span><button class="save-button" type="button" aria-label="<?php esc_attr_e( 'שמירה', 'tra-vel-v2' ); ?>"><i data-lucide="heart"></i></button></div><div class="deal-body"><div class="deal-meta"><?php echo esc_html( $deal['meta'] ); ?></div><h3 class="deal-title"><?php echo esc_html( $deal['title'] ); ?></h3><div class="deal-footer"><div class="deal-price"><small><?php esc_html_e( 'מחיר ותנאים לפי תאריכים והרכב', 'tra-vel-v2' ); ?></small><strong><?php echo esc_html( $deal['price'] ); ?></strong></div><a href="<?php echo esc_url( $map_url ); ?>" aria-label="<?php esc_attr_e( 'לפרטים', 'tra-vel-v2' ); ?>"><i data-lucide="arrow-left"></i></a></div></div></article>
		<?php endforeach; ?>
		<article class="deal-card"><div class="deal-media" style="background:linear-gradient(135deg,#0d3440,#0b6d7e)"><span class="deal-tag"><?php esc_html_e( 'התאמה לפי מסלול', 'tra-vel-v2' ); ?></span><span class="field-icon" style="position:absolute;inset:50% auto auto 50%;transform:translate(-50%,-50%);width:72px;height:72px"><i data-lucide="shield-check"></i></span></div><div class="deal-body"><div class="deal-meta"><?php esc_html_e( 'ביטוח נסיעות · השוואת כיסויים', 'tra-vel-v2' ); ?></div><h3 class="deal-title"><?php esc_html_e( 'כיסוי רפואי, כבודה וספורט בלי לנחש', 'tra-vel-v2' ); ?></h3><div class="deal-footer"><div class="deal-price"><small><?php esc_html_e( 'השוואה מותאמת לנסיעה', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'בדיקה', 'tra-vel-v2' ); ?></strong></div><a href="<?php echo esc_url( home_url( '/travel-insurance/' ) ); ?>"><i data-lucide="arrow-left"></i></a></div></div></article>
	</div></div></section>

	<section class="section dark" id="ai"><div class="page-width ai-panel"><div><span class="kicker"><i data-lucide="sparkles"></i>Tra-Vel AI Planner</span><h2><?php esc_html_e( 'ספרו לנו איך אתם רוצים להרגיש. נתחיל לסדר את הדרך.', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'המתכנן הופך תקציב, קצב, הרכב והעדפות לבקשה מסודרת, מציג מה הבין ושואל רק על מה שחסר.', 'tra-vel-v2' ); ?></p><a class="ai-input" href="<?php echo esc_url( $planner_url ); ?>"><i data-lucide="message-circle-more"></i><span><?php esc_html_e( '“טיול זוגי רגוע באסיה, 12 יום, בלי יותר מעצירה אחת...”', 'tra-vel-v2' ); ?></span><span class="ai-input-action"><?php esc_html_e( 'התחילו לתכנן', 'tra-vel-v2' ); ?></span></a></div><div class="ai-visual"><span class="ai-orb"><i data-lucide="sparkles"></i></span><article class="suggestion one"><i data-lucide="plane-takeoff"></i><span><small><?php esc_html_e( 'טיסה', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'קונקשן בכרטיס אחד עשוי לאזן זמן ופשטות', 'tra-vel-v2' ); ?></strong></span></article><article class="suggestion two"><i data-lucide="cloud-sun"></i><span><small><?php esc_html_e( 'עונה', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'סמנו איזה מזג אוויר מתאים לכם', 'tra-vel-v2' ); ?></strong></span></article><article class="suggestion three"><i data-lucide="route"></i><span><small><?php esc_html_e( 'קצב', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'בחרו בין מסלול רגוע למסלול מגוון', 'tra-vel-v2' ); ?></strong></span></article></div></div></section>

	<section class="section" id="guides"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'ידע שאפשר להזמין ממנו', 'tra-vel-v2' ); ?></span><h2><?php esc_html_e( 'מדריכים עמוקים, מחוברים למחירים', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'כל אזור, עונה ומסלול מתחברים למפה ולהצעה הרלוונטית.', 'tra-vel-v2' ); ?></p></div><a class="text-link" href="<?php echo esc_url( home_url( '/guides/' ) ); ?>"><?php esc_html_e( 'כל מדריכי היעדים', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></div><div class="guide-layout"><a class="featured-guide" href="<?php echo esc_url( $thailand_url ); ?>" style="background-image:linear-gradient(0deg,rgba(4,17,23,.9),transparent 65%),url('<?php echo tra_vel_v2_asset_uri( 'images/thailand.jpg' ); ?>')"><div class="featured-guide-content"><span><?php esc_html_e( 'מדריך עומק · 26 פרקים', 'tra-vel-v2' ); ?></span><h3><?php esc_html_e( 'תאילנד 2026: המסלול, התקציב והעונה שמתאימים לכם', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'מפת אזורים, טיסות, איים, מלונות, ביטוח וטעויות יקרות שכדאי למנוע.', 'tra-vel-v2' ); ?></p><b><?php esc_html_e( 'למדריך המלא', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></b></div></a><div class="guide-stack"><a class="guide-row" href="<?php echo esc_url( home_url( '/guides/flight-price/' ) ); ?>"><span class="guide-number">01</span><div><small><?php esc_html_e( 'תכנון', 'tra-vel-v2' ); ?></small><h3><?php esc_html_e( 'איך קוראים מחיר טיסה ומה באמת כלול', 'tra-vel-v2' ); ?></h3></div><i data-lucide="arrow-left"></i></a><a class="guide-row" href="<?php echo esc_url( home_url( '/guides/hidden-costs/' ) ); ?>"><span class="guide-number">02</span><div><small><?php esc_html_e( 'כסף', 'tra-vel-v2' ); ?></small><h3><?php esc_html_e( 'כבודה, המרה והעברות: העלויות שמתחבאות', 'tra-vel-v2' ); ?></h3></div><i data-lucide="arrow-left"></i></a><a class="guide-row" href="<?php echo esc_url( home_url( '/travel-insurance/' ) ); ?>"><span class="guide-number">03</span><div><small><?php esc_html_e( 'ביטחון', 'tra-vel-v2' ); ?></small><h3><?php esc_html_e( 'ביטוח נסיעות שמתאים למסלול ולא רק למחיר', 'tra-vel-v2' ); ?></h3></div><i data-lucide="arrow-left"></i></a></div></div></div></section>
</main>
<?php get_footer(); ?>
