<?php
/**
 * Tra-Vel V2 commercial discovery homepage.
 *
 * @package TraVelV2
 */

get_header();
$map_url       = home_url( '/travel-map/' );
$thailand_url  = home_url( '/thailand/' );
$planner_url   = home_url( '/ai-planner/' );
?>
<main id="main-content">
	<section class="home-hero">
		<div class="hero-grid page-width">
			<div class="hero-copy">
				<span class="kicker"><i data-lucide="sparkles"></i><?php esc_html_e( 'Tra-Vel Intelligence · מסע אחד, החלטה אחת בכל פעם', 'tra-vel-v2' ); ?></span>
				<h1><?php esc_html_e( 'כל העולם.', 'tra-vel-v2' ); ?><br><em><?php esc_html_e( 'על מפה אחת.', 'tra-vel-v2' ); ?></em></h1>
				<p><?php esc_html_e( 'בוחרים מקום על הגלובוס ומקבלים טיסות, מלונות, מסלולים, ביטוח ועלות אמיתית — עם הסבר מה עדיף ולמה.', 'tra-vel-v2' ); ?></p>
				<a class="ai-prompt" href="<?php echo esc_url( $planner_url ); ?>"><i data-lucide="bot"></i><span><?php esc_html_e( 'אפשר גם לכתוב:', 'tra-vel-v2' ); ?></span><strong><?php esc_html_e( '“שבועיים בתאילנד עד ₪9,000 לזוג”', 'tra-vel-v2' ); ?></strong><i data-lucide="arrow-left"></i></a>
			</div>
			<div class="globe-panel" aria-label="<?php esc_attr_e( 'מפת מחירים אינטראקטיבית', 'tra-vel-v2' ); ?>">
				<div class="globe-halo"></div>
				<div class="globe">
					<span class="origin-point" title="<?php esc_attr_e( 'תל אביב', 'tra-vel-v2' ); ?>"></span>
					<span class="route-curve curve-one"></span><span class="route-curve curve-two"></span>
					<button class="price-pin pin-budapest" data-destination="budapest" type="button">$214</button>
					<button class="price-pin pin-athens" data-destination="athens" type="button">$189</button>
					<button class="price-pin pin-dubai" data-destination="dubai" type="button">$236</button>
					<button class="price-pin pin-bangkok is-active" data-destination="bangkok" type="button">$742</button>
					<button class="price-pin pin-tokyo" data-destination="tokyo" type="button">$918</button>
					<button class="price-pin pin-lisbon" data-destination="lisbon" type="button">$327</button>
				</div>
				<div class="globe-tools"><button data-map-zoom="in" type="button" aria-label="<?php esc_attr_e( 'הגדלה', 'tra-vel-v2' ); ?>"><i data-lucide="plus"></i></button><button data-map-zoom="out" type="button" aria-label="<?php esc_attr_e( 'הקטנה', 'tra-vel-v2' ); ?>"><i data-lucide="minus"></i></button><a href="<?php echo esc_url( $map_url ); ?>" aria-label="<?php esc_attr_e( 'מפה מלאה', 'tra-vel-v2' ); ?>"><i data-lucide="maximize-2"></i></a></div>
				<article class="map-result" data-map-result>
					<img class="map-result-image" data-result-image src="<?php echo tra_vel_v2_asset_uri( 'images/thailand.jpg' ); ?>" alt="<?php esc_attr_e( 'בנגקוק, תאילנד', 'tra-vel-v2' ); ?>">
					<div class="map-result-body"><div class="result-top"><div><small><?php esc_html_e( 'ההצעה החכמה עכשיו', 'tra-vel-v2' ); ?></small><h3 data-result-city><?php esc_html_e( 'בנגקוק, תאילנד', 'tra-vel-v2' ); ?></h3></div><button class="save-button" type="button" aria-label="<?php esc_attr_e( 'שמירה', 'tra-vel-v2' ); ?>"><i data-lucide="heart"></i></button></div><div class="result-tags" data-result-tags><span><?php esc_html_e( '12 לילות', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'עצירה אחת', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'כולל כבודה', 'tra-vel-v2' ); ?></span></div><div class="result-price"><div><small><?php esc_html_e( 'לאדם, הלוך ושוב', 'tra-vel-v2' ); ?></small><strong data-result-price>$742</strong></div><p data-result-note><?php esc_html_e( 'חיסכון של $157 דרך דובאי', 'tra-vel-v2' ); ?></p></div></div>
				</article>
				<?php tra_vel_v2_demo_disclosure(); ?>
			</div>
		</div>
	</section>

	<section class="search-zone" id="search">
		<div class="page-width">
			<div class="product-tabs" role="tablist" aria-label="<?php esc_attr_e( 'סוג הזמנה', 'tra-vel-v2' ); ?>"><button class="is-active" type="button"><i data-lucide="package"></i><?php esc_html_e( 'טיסה + מלון', 'tra-vel-v2' ); ?></button><button type="button"><i data-lucide="plane"></i><?php esc_html_e( 'טיסות', 'tra-vel-v2' ); ?></button><button type="button"><i data-lucide="hotel"></i><?php esc_html_e( 'מלונות', 'tra-vel-v2' ); ?></button><button type="button"><i data-lucide="palmtree"></i><?php esc_html_e( 'חבילות', 'tra-vel-v2' ); ?></button><button type="button"><i data-lucide="shield-check"></i><?php esc_html_e( 'ביטוח', 'tra-vel-v2' ); ?></button></div>
			<form class="search-dock" action="<?php echo esc_url( $map_url ); ?>" method="get">
				<label class="search-field"><span class="field-icon"><i data-lucide="map-pin"></i></span><span><small><?php esc_html_e( 'מאיפה ולאן', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'תל אביב ← לא משנה לאן', 'tra-vel-v2' ); ?></strong></span><input class="sr-only" name="route" value="TLV-anywhere"></label>
				<label class="search-field"><span class="field-icon"><i data-lucide="calendar-range"></i></span><span><small><?php esc_html_e( 'מתי', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'גמיש · החודש הבא', 'tra-vel-v2' ); ?></strong></span><input class="sr-only" name="dates" value="flexible"></label>
				<label class="search-field"><span class="field-icon"><i data-lucide="users"></i></span><span><small><?php esc_html_e( 'מי נוסע', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( '2 מבוגרים', 'tra-vel-v2' ); ?></strong></span><input class="sr-only" name="travelers" value="2"></label>
				<button class="search-submit" type="submit"><i data-lucide="search"></i><span><?php esc_html_e( 'השוו הכל', 'tra-vel-v2' ); ?></span></button>
			</form>
			<div class="quick-links"><span><?php esc_html_e( 'רעיונות מהירים:', 'tra-vel-v2' ); ?></span><a href="<?php echo esc_url( add_query_arg( 'budget', '2500', $map_url ) ); ?>"><?php esc_html_e( 'עד ₪2,500', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( add_query_arg( 'direct', '1', $map_url ) ); ?>"><?php esc_html_e( 'טיסות ישירות', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( add_query_arg( 'family', '1', $map_url ) ); ?>"><?php esc_html_e( 'עם ילדים', 'tra-vel-v2' ); ?></a><a href="<?php echo esc_url( $map_url ); ?>"><?php esc_html_e( 'לא משנה לאן', 'tra-vel-v2' ); ?></a></div>
			<div class="intelligence-strip"><div><span class="strip-icon"><i data-lucide="trending-down"></i></span><span><small><?php esc_html_e( 'מחיר טוב באמת', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'נמדד מול 90 הימים האחרונים', 'tra-vel-v2' ); ?></strong></span></div><div><span class="strip-icon"><i data-lucide="calculator"></i></span><span><small><?php esc_html_e( 'עלות כוללת', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'כבודה, העברות וביטוח בפנים', 'tra-vel-v2' ); ?></strong></span></div><div><span class="strip-icon"><i data-lucide="route"></i></span><span><small><?php esc_html_e( 'מסלולים חכמים', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'ישיר, קונקשן ותחנות בדרך', 'tra-vel-v2' ); ?></strong></span></div><div><span class="strip-icon"><i data-lucide="badge-check"></i></span><span><small><?php esc_html_e( 'למה זה מתאים', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'יתרונות, חסרונות ורמת סיכון', 'tra-vel-v2' ); ?></strong></span></div></div>
		</div>
	</section>

	<section class="section" id="routes"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'אותו יעד, שלוש החלטות שונות', 'tra-vel-v2' ); ?></span><h2><?php esc_html_e( 'מהי הדרך החכמה לבנגקוק?', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'אנחנו לא בוחרים רק את הזול — אנחנו מסבירים את המחיר של כל בחירה בזמן, נוחות וגמישות.', 'tra-vel-v2' ); ?></p></div><a class="text-link" href="<?php echo esc_url( $map_url ); ?>"><?php esc_html_e( 'השוואה מלאה במפה', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></div>
		<div class="route-board"><header class="route-board-head"><div class="route-airports"><b class="airport-code">TLV</b><span><i data-lucide="plane"></i></span><b class="airport-code">BKK</b><small><?php esc_html_e( '12–26 בנובמבר · 2 נוסעים', 'tra-vel-v2' ); ?></small></div><span class="updated"><?php esc_html_e( 'נתוני הדגמה עד חיבור ספק', 'tra-vel-v2' ); ?></span></header><div class="route-cards">
			<button class="route-card" type="button" data-route data-route-summary="<?php esc_attr_e( 'ישיר — הכי נוח, במחיר גבוה יותר', 'tra-vel-v2' ); ?>"><div class="route-card-top"><span class="route-badge"><?php esc_html_e( 'הכי נוח', 'tra-vel-v2' ); ?></span><strong class="price">$899</strong></div><h3><?php esc_html_e( 'ישיר עם EL AL', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( '11:20 שעות · ללא החלפה', 'tra-vel-v2' ); ?></p><div class="route-data"><span><i data-lucide="clock-3"></i><?php esc_html_e( 'חוסך 5 שעות', 'tra-vel-v2' ); ?></span><span><i data-lucide="briefcase"></i><?php esc_html_e( 'כבודה כלולה', 'tra-vel-v2' ); ?></span><span><i data-lucide="shield"></i><?php esc_html_e( 'סיכון נמוך', 'tra-vel-v2' ); ?></span></div></button>
			<button class="route-card recommended is-selected" type="button" data-route data-route-summary="<?php esc_attr_e( 'דרך דובאי — הבחירה המאוזנת', 'tra-vel-v2' ); ?>"><div class="route-card-top"><span class="route-badge"><?php esc_html_e( 'הבחירה החכמה', 'tra-vel-v2' ); ?></span><strong class="price">$742</strong></div><h3><?php esc_html_e( 'דרך דובאי', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( '14:00 שעות · עצירה של 1:55', 'tra-vel-v2' ); ?></p><div class="route-data"><span><i data-lucide="piggy-bank"></i><?php esc_html_e( 'חיסכון $157', 'tra-vel-v2' ); ?></span><span><i data-lucide="coffee"></i><?php esc_html_e( 'עצירה נוחה', 'tra-vel-v2' ); ?></span><span><i data-lucide="shield-check"></i><?php esc_html_e( 'כרטיס אחד', 'tra-vel-v2' ); ?></span></div></button>
			<button class="route-card" type="button" data-route data-route-summary="<?php esc_attr_e( 'דרך אתונה — הכי זול, אך ארוך יותר', 'tra-vel-v2' ); ?>"><div class="route-card-top"><span class="route-badge"><?php esc_html_e( 'הכי זול', 'tra-vel-v2' ); ?></span><strong class="price">$621</strong></div><h3><?php esc_html_e( 'עצירת לילה באתונה', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( '24:30 שעות · כרטיסים נפרדים', 'tra-vel-v2' ); ?></p><div class="route-data"><span><i data-lucide="badge-dollar-sign"></i><?php esc_html_e( 'חיסכון $278', 'tra-vel-v2' ); ?></span><span><i data-lucide="bed-double"></i><?php esc_html_e( 'לילה בדרך', 'tra-vel-v2' ); ?></span><span><i data-lucide="triangle-alert"></i><?php esc_html_e( 'סיכון בינוני', 'tra-vel-v2' ); ?></span></div></button>
		</div><p class="updated" data-route-summary><?php esc_html_e( 'דרך דובאי — הבחירה המאוזנת: $157 פחות ורק 2:40 שעות יותר', 'tra-vel-v2' ); ?></p></div></div></section>

	<section class="section soft" id="deals"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'לא “מבצע” — הזדמנות שנבדקה', 'tra-vel-v2' ); ?></span><h2><?php esc_html_e( 'מחירים שכדאי לפעול עליהם', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'כל הצעה מקבלת הקשר: מה כלול, מול מה הושוותה ועד מתי כדאי להחליט.', 'tra-vel-v2' ); ?></p></div><a class="text-link" href="<?php echo esc_url( $map_url ); ?>"><?php esc_html_e( 'כל המחירים על המפה', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></div><div class="deal-grid">
		<?php
		$deals = array(
			array( 'image' => 'city-budapest.webp', 'tag' => 'ירד 14%', 'meta' => 'בודפשט · 4 לילות · 4★', 'title' => 'סופ״ש אורבני במרכז העיר', 'price' => '€389' ),
			array( 'image' => 'thailand.jpg', 'tag' => 'טיסה + מלון', 'meta' => 'קוסמוי · 10 לילות · 5★', 'title' => 'איים, ספא וביטול גמיש', 'price' => '$1,420' ),
			array( 'image' => 'city-vienna.webp', 'tag' => 'ישיר', 'meta' => 'וינה · 3 לילות · 4★', 'title' => 'תרבות, אוכל ומלון ליד הרינג', 'price' => '€449' ),
		);
		foreach ( $deals as $deal ) :
			?>
			<article class="deal-card"><div class="deal-media" style="background-image:url('<?php echo tra_vel_v2_asset_uri( 'images/' . $deal['image'] ); ?>')"><span class="deal-tag"><?php echo esc_html( $deal['tag'] ); ?></span><button class="save-button" type="button" aria-label="<?php esc_attr_e( 'שמירה', 'tra-vel-v2' ); ?>"><i data-lucide="heart"></i></button></div><div class="deal-body"><div class="deal-meta"><?php echo esc_html( $deal['meta'] ); ?></div><h3 class="deal-title"><?php echo esc_html( $deal['title'] ); ?></h3><div class="deal-footer"><div class="deal-price"><small><?php esc_html_e( 'לאדם בחדר זוגי · הדגמה', 'tra-vel-v2' ); ?></small><strong><?php echo esc_html( $deal['price'] ); ?></strong></div><a href="<?php echo esc_url( $map_url ); ?>" aria-label="<?php esc_attr_e( 'לפרטים', 'tra-vel-v2' ); ?>"><i data-lucide="arrow-left"></i></a></div></div></article>
		<?php endforeach; ?>
		<article class="deal-card"><div class="deal-media" style="background:linear-gradient(135deg,#0d3440,#0b6d7e)"><span class="deal-tag"><?php esc_html_e( 'המלצה לפי מסלול', 'tra-vel-v2' ); ?></span><span class="field-icon" style="position:absolute;inset:50% auto auto 50%;transform:translate(-50%,-50%);width:72px;height:72px"><i data-lucide="shield-check"></i></span></div><div class="deal-body"><div class="deal-meta"><?php esc_html_e( 'ביטוח נסיעות · השוואת כיסויים', 'tra-vel-v2' ); ?></div><h3 class="deal-title"><?php esc_html_e( 'כיסוי רפואי, כבודה וספורט — בלי לנחש', 'tra-vel-v2' ); ?></h3><div class="deal-footer"><div class="deal-price"><small><?php esc_html_e( 'הצעה מותאמת לנסיעה', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'בדיקה', 'tra-vel-v2' ); ?></strong></div><a href="<?php echo esc_url( home_url( '/travel-insurance/' ) ); ?>"><i data-lucide="arrow-left"></i></a></div></div></article>
	</div></div></section>

	<section class="section dark" id="ai"><div class="page-width ai-panel"><div><span class="kicker"><i data-lucide="sparkles"></i>Tra-Vel AI Planner</span><h2><?php esc_html_e( 'ספרו לנו איך אתם רוצים להרגיש. אנחנו נבנה את הדרך.', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'המתכנן משלב תקציב, מזג אוויר, זמני טיסה, קצב, ילדים, מלון, תחבורה וביטוח — ומציג כל החלטה על המפה.', 'tra-vel-v2' ); ?></p><a class="ai-input" href="<?php echo esc_url( $planner_url ); ?>"><i data-lucide="message-circle-more"></i><span><?php esc_html_e( '“טיול זוגי רגוע באסיה, 12 יום, בלי יותר מעצירה אחת...”', 'tra-vel-v2' ); ?></span><span class="ai-input-action"><?php esc_html_e( 'בנו לי מסלול', 'tra-vel-v2' ); ?></span></a></div><div class="ai-visual"><span class="ai-orb"><i data-lucide="sparkles"></i></span><article class="suggestion one"><i data-lucide="plane-takeoff"></i><span><small><?php esc_html_e( 'טיסה', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'דרך דובאי חוסכת ₪580', 'tra-vel-v2' ); ?></strong></span></article><article class="suggestion two"><i data-lucide="cloud-sun"></i><span><small><?php esc_html_e( 'מזג אוויר', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'קוסמוי פחות מתאימה בנובמבר', 'tra-vel-v2' ); ?></strong></span></article><article class="suggestion three"><i data-lucide="route"></i><span><small><?php esc_html_e( 'שינוי חכם', 'tra-vel-v2' ); ?></small><strong><?php esc_html_e( 'התחילו בצ׳יאנג מאי וסיימו בפוקט', 'tra-vel-v2' ); ?></strong></span></article></div></div></section>

	<section class="section" id="guides"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'ידע שאפשר להזמין ממנו', 'tra-vel-v2' ); ?></span><h2><?php esc_html_e( 'מדריכים עמוקים, מחוברים למחירים', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'כל אזור, עונה ומסלול מתחברים למפה ולהצעה הרלוונטית.', 'tra-vel-v2' ); ?></p></div><a class="text-link" href="<?php echo esc_url( home_url( '/guides/' ) ); ?>"><?php esc_html_e( 'כל מדריכי היעדים', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></div><div class="guide-layout"><a class="featured-guide" href="<?php echo esc_url( $thailand_url ); ?>" style="background-image:linear-gradient(0deg,rgba(4,17,23,.9),transparent 65%),url('<?php echo tra_vel_v2_asset_uri( 'images/thailand.jpg' ); ?>')"><div class="featured-guide-content"><span><?php esc_html_e( 'מדריך הדגל · 18 פרקים', 'tra-vel-v2' ); ?></span><h3><?php esc_html_e( 'תאילנד 2026: המסלול, התקציב והעונה שמתאימים לכם', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'מפת אזורים, טיסות, איים, מלונות, ביטוח וטעויות יקרות שכדאי למנוע.', 'tra-vel-v2' ); ?></p><b><?php esc_html_e( 'למדריך המלא', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></b></div></a><div class="guide-stack"><a class="guide-row" href="<?php echo esc_url( home_url( '/guides/flight-price/' ) ); ?>"><span class="guide-number">01</span><div><small><?php esc_html_e( 'תכנון', 'tra-vel-v2' ); ?></small><h3><?php esc_html_e( 'איך קוראים מחיר טיסה — ומה באמת כלול', 'tra-vel-v2' ); ?></h3></div><i data-lucide="arrow-left"></i></a><a class="guide-row" href="<?php echo esc_url( home_url( '/guides/hidden-costs/' ) ); ?>"><span class="guide-number">02</span><div><small><?php esc_html_e( 'כסף', 'tra-vel-v2' ); ?></small><h3><?php esc_html_e( 'כבודה, המרה והעברות: העלויות שמתחבאות', 'tra-vel-v2' ); ?></h3></div><i data-lucide="arrow-left"></i></a><a class="guide-row" href="<?php echo esc_url( home_url( '/travel-insurance/' ) ); ?>"><span class="guide-number">03</span><div><small><?php esc_html_e( 'ביטחון', 'tra-vel-v2' ); ?></small><h3><?php esc_html_e( 'ביטוח נסיעות שמתאים למסלול — לא רק למחיר', 'tra-vel-v2' ); ?></h3></div><i data-lucide="arrow-left"></i></a></div></div></div></section>
</main>
<?php get_footer(); ?>
