<?php
/**
 * Template Name: Tra-Vel Destination Guide
 * Template Post Type: page, destination
 *
 * @package TraVelV2
 */

get_header();

while ( have_posts() ) :
	the_post();
	$hero = get_the_post_thumbnail_url( get_the_ID(), 'tra-vel-hero' );
	if ( ! $hero ) {
		$hero = tra_vel_v2_asset_uri( 'images/thailand.jpg' );
	}
	$title = get_the_title() ?: __( 'תאילנד', 'tra-vel-v2' );
	?>
	<main id="main-content">
		<section class="destination-hero"><img src="<?php echo esc_url( $hero ); ?>" alt="<?php echo esc_attr( $title ); ?>">
			<div class="destination-hero-content page-width"><div class="breadcrumbs"><a href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php esc_html_e( 'ראשי', 'tra-vel-v2' ); ?></a><i data-lucide="chevron-left"></i><a href="<?php echo esc_url( home_url( '/destinations/' ) ); ?>"><?php esc_html_e( 'יעדים', 'tra-vel-v2' ); ?></a><i data-lucide="chevron-left"></i><span><?php echo esc_html( $title ); ?></span></div><span class="destination-badge"><i data-lucide="badge-check"></i><?php printf( esc_html__( 'מדריך עומק · עודכן %s', 'tra-vel-v2' ), esc_html( get_the_modified_date( 'F Y' ) ) ); ?></span><h1><?php echo esc_html( $title ); ?>.<br><em><?php esc_html_e( 'הטיול שלכם, לא של כולם.', 'tra-vel-v2' ); ?></em></h1><p><?php echo esc_html( get_the_excerpt() ?: __( 'עונות, אזורים, טיסות, מלונות ועלויות — מחוברים למפה שמציעה מסלול לפי התקציב והקצב שלכם, ומסבירה כל בחירה.', 'tra-vel-v2' ) ); ?></p><div class="destination-actions"><a href="<?php echo esc_url( home_url( '/travel-map/' ) ); ?>"><i data-lucide="route"></i><?php esc_html_e( 'בנו מסלול על המפה', 'tra-vel-v2' ); ?></a><button type="button"><i data-lucide="sparkles"></i><?php esc_html_e( 'שאלו את המתכנן', 'tra-vel-v2' ); ?></button><button type="button"><i data-lucide="bookmark"></i><?php esc_html_e( 'שמרו מדריך', 'tra-vel-v2' ); ?></button></div></div>
		</section>
		<div class="fact-ribbon page-width"><div><small><?php esc_html_e( 'זמן טיסה ישירה', 'tra-vel-v2' ); ?></small><strong><?php echo esc_html( get_post_meta( get_the_ID(), 'flight_time', true ) ?: 'כ־11:20 שעות' ); ?></strong></div><div><small><?php esc_html_e( 'תקציב יומי לזוג', 'tra-vel-v2' ); ?></small><strong><?php echo esc_html( get_post_meta( get_the_ID(), 'daily_budget', true ) ?: '₪450–₪1,100' ); ?></strong></div><div><small><?php esc_html_e( 'חלון מומלץ', 'tra-vel-v2' ); ?></small><strong><?php echo esc_html( get_post_meta( get_the_ID(), 'best_season', true ) ?: 'נובמבר–פברואר' ); ?></strong></div><div><small><?php esc_html_e( 'מתאים במיוחד', 'tra-vel-v2' ); ?></small><strong><?php echo esc_html( get_post_meta( get_the_ID(), 'best_for', true ) ?: 'זוגות · משפחות · טיול גדול' ); ?></strong></div></div>
		<nav class="article-tabs page-width" aria-label="<?php esc_attr_e( 'תוכן המדריך', 'tra-vel-v2' ); ?>"><a href="#map"><?php esc_html_e( 'מפת מסלול', 'tra-vel-v2' ); ?></a><a href="#when"><?php esc_html_e( 'מתי לטוס', 'tra-vel-v2' ); ?></a><a href="#areas"><?php esc_html_e( 'איפה לישון', 'tra-vel-v2' ); ?></a><a href="#costs"><?php esc_html_e( 'עלויות', 'tra-vel-v2' ); ?></a><a href="#flights"><?php esc_html_e( 'טיסות', 'tra-vel-v2' ); ?></a><a href="#insurance"><?php esc_html_e( 'ביטוח', 'tra-vel-v2' ); ?></a><a href="#guide"><?php esc_html_e( 'המדריך המלא', 'tra-vel-v2' ); ?></a></nav>

		<section class="article-section" id="map"><div class="destination-map-band page-width"><div class="destination-map-copy"><span class="eyebrow"><?php esc_html_e( 'המפה היא גם המתכנן', 'tra-vel-v2' ); ?></span><h2><?php esc_html_e( 'בחרו נקודה. קבלו את הצעד הבא.', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'מתחילים בתל אביב, בוחרים יעד, ואז משווים מסלול ישיר, מעבר חכם או עצירת לילה. המפה מחברת גם עונות, מלונות, תחבורה וביטוח.', 'tra-vel-v2' ); ?></p><ul><li><i data-lucide="badge-dollar-sign"></i><?php esc_html_e( 'מחיר כולל ולא רק מחיר הכותרת', 'tra-vel-v2' ); ?></li><li><i data-lucide="clock-3"></i><?php esc_html_e( 'זמן אמיתי מדלת לדלת', 'tra-vel-v2' ); ?></li><li><i data-lucide="triangle-alert"></i><?php esc_html_e( 'סיכון בכרטיסים נפרדים ובקונקשן', 'tra-vel-v2' ); ?></li><li><i data-lucide="sparkles"></i><?php esc_html_e( 'הצעה יזומה לשיפור המסלול', 'tra-vel-v2' ); ?></li></ul><a class="header-cta" href="<?php echo esc_url( home_url( '/travel-map/' ) ); ?>"><?php esc_html_e( 'פתחו מסך מפה מלא', 'tra-vel-v2' ); ?></a></div><div class="compact-map"><div class="globe"><span class="origin-point"></span><span class="route-curve curve-one"></span><button class="price-pin pin-dubai" data-destination="dubai" type="button">$236</button><button class="price-pin pin-bangkok is-active" data-destination="bangkok" type="button">$742</button></div><article class="map-result" data-map-result><img class="map-result-image" data-result-image src="<?php echo tra_vel_v2_asset_uri( 'images/thailand.jpg' ); ?>" alt="<?php echo esc_attr( $title ); ?>"><div class="map-result-body"><div class="result-top"><div><small><?php esc_html_e( 'המסלול המומלץ', 'tra-vel-v2' ); ?></small><h3 data-result-city><?php echo esc_html( $title ); ?></h3></div></div><div class="result-tags" data-result-tags><span><?php esc_html_e( '12 לילות', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'עצירה אחת', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'כולל כבודה', 'tra-vel-v2' ); ?></span></div><div class="result-price"><div><small><?php esc_html_e( 'החל מ־ · הדגמה', 'tra-vel-v2' ); ?></small><strong data-result-price>$742</strong></div><p data-result-note><?php esc_html_e( 'חיסכון של $157 דרך דובאי', 'tra-vel-v2' ); ?></p></div></div></article></div></div></section>

		<section class="article-section" id="when"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'מחיר, מזג אוויר ועומס באותה תמונה', 'tra-vel-v2' ); ?></span><h2><?php printf( esc_html__( 'מתי כדאי לטוס ל%s?', 'tra-vel-v2' ), esc_html( $title ) ); ?></h2><p><?php esc_html_e( 'אין חודש אחד נכון. יש שילוב שמתאים למסלול, לאזורים ולרמת הגמישות שלכם.', 'tra-vel-v2' ); ?></p></div></div><div class="month-grid"><div class="month-cell"><span><?php esc_html_e( 'אוקטובר', 'tra-vel-v2' ); ?></span><strong>$690</strong><small><?php esc_html_e( 'מעבר עונות', 'tra-vel-v2' ); ?></small></div><div class="month-cell best"><b><?php esc_html_e( 'איזון מומלץ', 'tra-vel-v2' ); ?></b><span><?php esc_html_e( 'נובמבר', 'tra-vel-v2' ); ?></span><strong>$742</strong><small><?php esc_html_e( 'תנאים טובים', 'tra-vel-v2' ); ?></small></div><div class="month-cell"><span><?php esc_html_e( 'דצמבר', 'tra-vel-v2' ); ?></span><strong>$910</strong><small><?php esc_html_e( 'עונה גבוהה', 'tra-vel-v2' ); ?></small></div><div class="month-cell"><span><?php esc_html_e( 'ינואר', 'tra-vel-v2' ); ?></span><strong>$835</strong><small><?php esc_html_e( 'יבש ועמוס', 'tra-vel-v2' ); ?></small></div><div class="month-cell"><span><?php esc_html_e( 'פברואר', 'tra-vel-v2' ); ?></span><strong>$778</strong><small><?php esc_html_e( 'נעים וחם', 'tra-vel-v2' ); ?></small></div><div class="month-cell"><span><?php esc_html_e( 'מרץ', 'tra-vel-v2' ); ?></span><strong>$720</strong><small><?php esc_html_e( 'חם יותר', 'tra-vel-v2' ); ?></small></div></div></div></section>

		<section class="article-section" id="areas"><div class="page-width"><div class="section-heading"><div><span class="eyebrow"><?php esc_html_e( 'איפה תהיו — ואיך זה מרגיש', 'tra-vel-v2' ); ?></span><h2><?php esc_html_e( 'אזורי הלינה שמעצבים את הטיול', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'מתחילים מסוג החוויה וממשיכים לאזור, נכס וחדר — לא מרשימת מלונות אינסופית.', 'tra-vel-v2' ); ?></p></div></div><div class="area-grid"><article class="area-card"><span>01 · <?php esc_html_e( 'עיר', 'tra-vel-v2' ); ?></span><h3><?php esc_html_e( 'מרכז וקצב', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'אוכל, שווקים, מלונות מצוינים וכניסה נוחה למסלול.', 'tra-vel-v2' ); ?></p><small><?php esc_html_e( 'מומלץ: 3–4 לילות', 'tra-vel-v2' ); ?></small><footer><strong>₪280–₪850</strong><a href="#map"><?php esc_html_e( 'ראו על המפה', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></footer></article><article class="area-card"><span>02 · <?php esc_html_e( 'טבע', 'tra-vel-v2' ); ?></span><h3><?php esc_html_e( 'צפון רגוע', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'קצב איטי, טבע, אוכל מקומי וטיולי יום.', 'tra-vel-v2' ); ?></p><small><?php esc_html_e( 'מומלץ: 3–5 לילות', 'tra-vel-v2' ); ?></small><footer><strong>₪180–₪620</strong><a href="#map"><?php esc_html_e( 'ראו על המפה', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></footer></article><article class="area-card"><span>03 · <?php esc_html_e( 'חוף', 'tra-vel-v2' ); ?></span><h3><?php esc_html_e( 'איים וחופים', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'בסיס לטיולי ים ומבחר רחב לזוגות ולמשפחות.', 'tra-vel-v2' ); ?></p><small><?php esc_html_e( 'מומלץ: 4–7 לילות', 'tra-vel-v2' ); ?></small><footer><strong>₪260–₪1,200</strong><a href="#map"><?php esc_html_e( 'ראו על המפה', 'tra-vel-v2' ); ?> <i data-lucide="arrow-left"></i></a></footer></article></div></div></section>

		<section class="article-section" id="guide"><div class="longform-layout page-width"><aside class="article-toc"><strong><?php esc_html_e( 'במדריך', 'tra-vel-v2' ); ?></strong><a href="#intro"><?php esc_html_e( 'איך מתחילים', 'tra-vel-v2' ); ?></a><a href="#flights"><?php esc_html_e( 'טיסות', 'tra-vel-v2' ); ?></a><a href="#costs"><?php esc_html_e( 'תקציב', 'tra-vel-v2' ); ?></a><a href="#insurance"><?php esc_html_e( 'ביטוח', 'tra-vel-v2' ); ?></a><a href="#faq"><?php esc_html_e( 'שאלות', 'tra-vel-v2' ); ?></a></aside><article class="article-prose"><span class="eyebrow"><?php esc_html_e( 'תבנית עריכה למדריך עומק של 5,000+ מילים', 'tra-vel-v2' ); ?></span>
			<?php if ( trim( wp_strip_all_tags( get_the_content() ) ) ) : ?>
				<?php the_content(); ?>
			<?php else : ?>
				<h2 id="intro"><?php printf( esc_html__( 'איך מתכננים %s בלי להעתיק מסלול של מישהו אחר', 'tra-vel-v2' ), esc_html( $title ) ); ?></h2><p class="lead"><?php esc_html_e( 'המסלול הנכון מתחיל במספר הימים, האנשים והקצב — ורק אחר כך ברשימת המקומות. כל פרק במדריך צריך לעזור לקבל החלטה, להשוות חלופה או לבצע את הצעד הבא.', 'tra-vel-v2' ); ?></p><blockquote><?php esc_html_e( 'לפני פרסום, יש להחליף את תוכן ההדגמה במדריך ערוך, מתועד ומתוארך בהיקף המתאים לנושא — בדרך כלל 5,000 מילים ומעלה למדריך דגל.', 'tra-vel-v2' ); ?></blockquote><div class="inline-data"><span class="data-icon"><i data-lucide="database"></i></span><div><h3><?php esc_html_e( 'מה מחובר לנתונים חיים?', 'tra-vel-v2' ); ?></h3><p><?php esc_html_e( 'טיסות, זמינות ומחירי מלונות, מטבע, מזג אוויר, זמני נסיעה והתראות. עובדות עריכה והמלצות מומחה דורשות מקור ותאריך בדיקה.', 'tra-vel-v2' ); ?></p></div></div><h2 id="flights"><?php esc_html_e( 'טיסה ישירה או קונקשן?', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'ההשוואה צריכה לכלול זמן כולל, טרמינל, כבודה, הגנת קונקשן, מדיניות שינוי וסיכון בכרטיסים נפרדים. כאשר עצירת לילה יוצרת חופשה טובה וזולה יותר, המערכת תציע אותה באופן יזום.', 'tra-vel-v2' ); ?></p><h2 id="costs"><?php esc_html_e( 'כמה עולה הטיול?', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'התקציב יוצג כטווח לפי סגנון ויורכב מטיסה, לינה, תחבורה, אוכל, אטרקציות, תקשורת וביטוח. המשתמש יוכל להזיז רכיב ולראות כיצד המסלול משתנה.', 'tra-vel-v2' ); ?></p><h2 id="insurance"><?php esc_html_e( 'ביטוח שמתאים למה שבאמת עושים', 'tra-vel-v2' ); ?></h2><p><?php esc_html_e( 'הצעת הביטוח תופיע רק אחרי שהמערכת מבינה את משך הנסיעה, הגילאים והפעילויות, ותפנה לרכישה מול ספק מורשה עם גילוי נאות.', 'tra-vel-v2' ); ?></p><h2 id="faq"><?php esc_html_e( 'שאלות נפוצות', 'tra-vel-v2' ); ?></h2><div class="faq-list"><details open><summary><?php esc_html_e( 'כמה ימים צריך?', 'tra-vel-v2' ); ?></summary><p><?php esc_html_e( 'התשובה תיגזר מהאזורים, זמני המעבר וקצב הנסיעה — ולא ממספר אחד שמתאים לכולם.', 'tra-vel-v2' ); ?></p></details><details><summary><?php esc_html_e( 'האם להזמין טיסה ומלון יחד?', 'tra-vel-v2' ); ?></summary><p><?php esc_html_e( 'משווים מחיר כולל, תנאי ביטול, סוג חדר, כבודה וגמישות זה לצד זה.', 'tra-vel-v2' ); ?></p></details></div>
			<?php endif; ?>
		</article></div></section>
	</main>
	<?php
endwhile;

get_footer();
