<?php
/**
 * Template Name: Tra-Vel Globe
 * Template Post Type: page
 *
 * @package TraVelV2
 */

get_header();
?>
<main id="main-content" class="theme-map-shell">
	<div class="map-workspace">
		<aside class="filter-panel" aria-label="<?php esc_attr_e( 'מסנני מסע', 'tra-vel-v2' ); ?>">
			<button class="round-button" data-filter-close type="button" aria-label="<?php esc_attr_e( 'סגירת מסננים', 'tra-vel-v2' ); ?>" style="float:left"><i data-lucide="x"></i></button>
			<span class="eyebrow">Tra-Vel Globe</span><h1><?php esc_html_e( 'לאן אפשר להגיע?', 'tra-vel-v2' ); ?></h1><p><?php esc_html_e( 'שנו את מה שחשוב לכם — המפה וההמלצה מתעדכנות יחד.', 'tra-vel-v2' ); ?></p>
			<div class="filter-block"><div class="budget-row"><strong><?php esc_html_e( 'תקציב לאדם', 'tra-vel-v2' ); ?></strong><span class="budget-value" data-budget-value>$950</span></div><input data-budget type="range" min="200" max="1600" step="25" value="950" aria-label="<?php esc_attr_e( 'תקציב', 'tra-vel-v2' ); ?>"><div class="filter-scale"><span>$200</span><span>$1,600</span></div></div>
			<div class="filter-block"><strong><?php esc_html_e( 'מה מחפשים?', 'tra-vel-v2' ); ?></strong><div class="filter-chips" data-filter-kind="trip"><button class="is-active" data-filter-value="all" type="button"><?php esc_html_e( 'הכל', 'tra-vel-v2' ); ?></button><button data-filter-value="flight" type="button"><?php esc_html_e( 'טיסה', 'tra-vel-v2' ); ?></button><button data-filter-value="package" type="button"><?php esc_html_e( 'טיסה + מלון', 'tra-vel-v2' ); ?></button><button data-filter-value="short" type="button"><?php esc_html_e( 'חופשה קצרה', 'tra-vel-v2' ); ?></button><button data-filter-value="long" type="button"><?php esc_html_e( 'טיול גדול', 'tra-vel-v2' ); ?></button></div></div>
			<div class="filter-block"><strong><?php esc_html_e( 'הקצב שלי', 'tra-vel-v2' ); ?></strong><label class="check-row"><input type="checkbox" checked> <?php esc_html_e( 'עד עצירה אחת', 'tra-vel-v2' ); ?></label><label class="check-row"><input type="checkbox" checked> <?php esc_html_e( 'לא יותר מ־16 שעות', 'tra-vel-v2' ); ?></label><label class="check-row"><input type="checkbox"> <?php esc_html_e( 'אפשר עצירת לילה בדרך', 'tra-vel-v2' ); ?></label><div class="toggle-row"><span><?php esc_html_e( 'רק טיסות ישירות', 'tra-vel-v2' ); ?></span><button class="toggle" data-direct-filter type="button" aria-pressed="false" aria-label="<?php esc_attr_e( 'טיסות ישירות בלבד', 'tra-vel-v2' ); ?>"></button></div></div>
			<div class="filter-block"><strong><?php esc_html_e( 'מה חשוב יותר?', 'tra-vel-v2' ); ?></strong><div class="filter-chips" data-filter-kind="sort"><button class="is-active" data-filter-value="smart" type="button"><?php esc_html_e( 'איזון', 'tra-vel-v2' ); ?></button><button data-filter-value="price" type="button"><?php esc_html_e( 'המחיר', 'tra-vel-v2' ); ?></button><button data-filter-value="time" type="button"><?php esc_html_e( 'זמן', 'tra-vel-v2' ); ?></button><button data-filter-value="smart" type="button"><?php esc_html_e( 'נוחות', 'tra-vel-v2' ); ?></button><button data-filter-value="smart" type="button"><?php esc_html_e( 'גמישות', 'tra-vel-v2' ); ?></button></div></div>
			<div class="filter-block"><strong><?php esc_html_e( 'עם מי נוסעים?', 'tra-vel-v2' ); ?></strong><div class="filter-chips"><button class="is-active" type="button"><?php esc_html_e( 'זוג', 'tra-vel-v2' ); ?></button><button type="button"><?php esc_html_e( 'משפחה', 'tra-vel-v2' ); ?></button><button type="button"><?php esc_html_e( 'לבד', 'tra-vel-v2' ); ?></button><button type="button"><?php esc_html_e( 'חברים', 'tra-vel-v2' ); ?></button></div></div>
			<button class="filter-apply" data-discovery-apply type="button"><?php esc_html_e( 'הציגו אפשרויות מתאימות', 'tra-vel-v2' ); ?></button>
		</aside>
		<section class="world-canvas" data-map-canvas data-data-mode="loading" aria-label="<?php esc_attr_e( 'גלובוס מחירים ומסלולים', 'tra-vel-v2' ); ?>">
			<form class="map-search-floating" action="<?php echo esc_url( home_url( '/travel-map/' ) ); ?>" method="get"><i data-lucide="sparkles"></i><input name="q" aria-label="<?php esc_attr_e( 'חיפוש חופשה', 'tra-vel-v2' ); ?>" value="<?php echo esc_attr( isset( $_GET['q'] ) ? sanitize_text_field( wp_unslash( $_GET['q'] ) ) : 'שבועיים בתאילנד בנובמבר, עד $950 לאדם' ); ?>"><button type="submit" aria-label="<?php esc_attr_e( 'חיפוש', 'tra-vel-v2' ); ?>"><i data-lucide="arrow-left"></i></button></form>
			<div class="globe"><span class="origin-point"></span><span class="route-curve curve-one"></span><span class="route-curve curve-two"></span><button class="price-pin pin-budapest" data-destination="budapest" type="button">$214</button><button class="price-pin pin-athens" data-destination="athens" type="button">$189</button><button class="price-pin pin-dubai" data-destination="dubai" type="button">$236</button><button class="price-pin pin-bangkok is-active" data-destination="bangkok" type="button">$742</button><button class="price-pin pin-tokyo" data-destination="tokyo" type="button">$918</button><button class="price-pin pin-lisbon" data-destination="lisbon" type="button">$327</button></div>
			<div class="map-layer-buttons"><button data-map-zoom="in" type="button" aria-label="<?php esc_attr_e( 'הגדלה', 'tra-vel-v2' ); ?>"><i data-lucide="plus"></i></button><button data-map-zoom="out" type="button" aria-label="<?php esc_attr_e( 'הקטנה', 'tra-vel-v2' ); ?>"><i data-lucide="minus"></i></button><button class="is-active" data-map-layer="deals" type="button" aria-pressed="true" aria-label="<?php esc_attr_e( 'מחירים', 'tra-vel-v2' ); ?>"><i data-lucide="badge-dollar-sign"></i></button><button data-map-layer="hotels" type="button" aria-pressed="false" aria-label="<?php esc_attr_e( 'מלונות', 'tra-vel-v2' ); ?>"><i data-lucide="bed-double"></i></button><button data-map-layer="airports" type="button" aria-pressed="false" aria-label="<?php esc_attr_e( 'שדות תעופה', 'tra-vel-v2' ); ?>"><i data-lucide="plane"></i></button><button data-map-layer="weather" type="button" aria-pressed="false" aria-label="<?php esc_attr_e( 'מזג אוויר', 'tra-vel-v2' ); ?>"><i data-lucide="cloud-sun"></i></button></div>
			<p class="map-data-status" data-layer-status role="status"><?php esc_html_e( 'טוען מנוע גילוי...', 'tra-vel-v2' ); ?></p><a class="map-weather-attribution" data-weather-attribution href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer" hidden>Weather data by Open-Meteo · CC BY 4.0</a>
			<article class="map-result" data-map-result style="left:20px;bottom:190px"><img class="map-result-image" data-result-image src="<?php echo tra_vel_v2_asset_uri( 'images/thailand.jpg' ); ?>" alt="<?php esc_attr_e( 'בנגקוק', 'tra-vel-v2' ); ?>"><div class="map-result-body"><div class="result-top"><div><small><?php esc_html_e( 'היעד הפעיל', 'tra-vel-v2' ); ?></small><h3 data-result-city><?php esc_html_e( 'בנגקוק, תאילנד', 'tra-vel-v2' ); ?></h3></div><button class="save-button" type="button"><i data-lucide="heart"></i></button></div><div class="result-tags" data-result-tags><span><?php esc_html_e( '12 לילות', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'עצירה אחת', 'tra-vel-v2' ); ?></span><span><?php esc_html_e( 'כולל כבודה', 'tra-vel-v2' ); ?></span></div><div class="result-facts"><span data-result-airport>BKK · 11:20</span><span data-result-hotel>Siam · 4.6★</span><span data-result-weather>29°C</span></div><div class="result-price"><div><small><?php esc_html_e( 'מחיר כולל לאדם', 'tra-vel-v2' ); ?></small><strong data-result-total>$1,347</strong></div><p><span data-result-price>$742</span> <span data-result-note><?php esc_html_e( 'טיסה לדוגמה', 'tra-vel-v2' ); ?></span></p></div></div></article>
			<aside class="route-sheet"><div class="sheet-head"><div><span class="eyebrow"><?php esc_html_e( 'ההחלטה הבאה שלכם', 'tra-vel-v2' ); ?></span><h2 data-route-title><?php esc_html_e( 'תל אביב ← בנגקוק · השוואת עלות מלאה', 'tra-vel-v2' ); ?></h2></div><span><?php esc_html_e( 'מחירי הדגמה · זמינות תתחבר בשלב הספקים', 'tra-vel-v2' ); ?></span></div><div class="mini-routes" data-route-list aria-live="polite"></div></aside>
		</section>
	</div>
</main>
<?php get_footer(); ?>
